import Link from "next/link"
import { ArrowRight, BriefcaseBusiness, Building2, CheckCircle2, CirclePlus, Compass, MapPin, Package, Search, UserRound } from "lucide-react"
import { createClient } from "@/lib/supabase/server"

type Listing = { id: string; title: string; created_at: string; skills_required?: string[] | null; company_name?: string | null; location?: string | null; budget?: number | null; category?: string | null }
const score = (item: Listing, skills: string[]) => { const required = item.skills_required?.map(x => x.toLowerCase()) || []; return skills.reduce((n, s) => n + Number(required.includes(s.toLowerCase())), 0) }
const rank = <T extends Listing>(items: T[], skills: string[]) => [...items].sort((a, b) => score(b, skills) - score(a, skills) || +new Date(b.created_at) - +new Date(a.created_at)).slice(0, 4)

function Section({ title, href, label, children }: { title: string; href: string; label: string; children: React.ReactNode }) { return <section className="min-w-0 max-w-full"><div className="mb-4 flex flex-wrap items-start justify-between gap-x-4 gap-y-2"><h2 className="min-w-0 text-h3 font-extrabold text-brand-midnight">{title}</h2><Link href={href} className="flex items-center gap-1 text-body-sm font-bold text-brand-indigo">{label} <ArrowRight className="h-4 w-4 shrink-0" /></Link></div>{children}</section> }
function Empty({ text, href, label }: { text: string; href: string; label: string }) { return <div className="rounded-card border border-dashed border-brand-borderLight bg-white px-6 py-10 text-center"><p className="text-body-sm text-brand-slate">{text}</p><Link href={href} className="mt-3 inline-block text-body-sm font-bold text-brand-indigo">{label}</Link></div> }

export default async function HomeHub() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser()
  if (!user) return <main className="min-h-screen bg-brand-ivory px-4 py-20 text-center"><h1 className="text-h1 font-extrabold text-brand-midnight">Your next opportunity starts here.</h1><Link href="/login" className="mt-6 inline-block rounded-xl bg-brand-indigo px-5 py-3 font-bold text-white">Join GigWay</Link></main>
  const [{ data: profile }, { data: jobs }, { data: projects }, { data: gigs }, { data: people }, { data: organizations }, { count: unread }, { count: applications }, { count: proposals }] = await Promise.all([
    supabase.from("profiles").select("full_name,avatar_url,tagline,bio,skills,location,user_roles,find_work_type,hire_talent_type").eq("id", user.id).maybeSingle(),
    supabase.from("jobs").select("id,title,company_name,location,skills_required,created_at").eq("status", "active").order("created_at", { ascending: false }).limit(12),
    supabase.from("projects").select("id,title,budget,category,skills_required,created_at").eq("status", "open").order("created_at", { ascending: false }).limit(12),
    supabase.from("gigs").select("id,title,price,delivery_days,image_url,category").eq("status", "active").order("created_at", { ascending: false }).limit(4),
    supabase.from("profiles").select("id,full_name,username,avatar_url,tagline,skills,availability,is_verified").eq("profile_completed", true).neq("id", user.id).order("created_at", { ascending: false }).limit(4),
    supabase.from("organizations").select("id,name,username,logo_url,tagline,industry,location,is_verified").order("created_at", { ascending: false }).limit(4),
    supabase.from("messages").select("id", { count: "exact", head: true }).eq("receiver_id", user.id).eq("is_read", false),
    supabase.from("job_applications").select("id", { count: "exact", head: true }).eq("applicant_id", user.id),
    supabase.from("proposals").select("id", { count: "exact", head: true }).eq("freelancer_id", user.id),
  ])
  const skills = (profile?.skills as string[] | null) || []; const first = profile?.full_name?.split(" ")[0] || "there"; const incomplete = [profile?.avatar_url, profile?.tagline || profile?.bio, skills.length, profile?.location].filter(Boolean).length < 4
  const roles = (profile?.user_roles as string[] | null) || []; const canHire = roles.includes("hire_talent"); const canWork = roles.includes("find_work")
  const opportunities = [...rank(jobs || [], skills).map(x => ({ ...x, kind: "Job", href: `/jobs/${x.id}` })), ...rank(projects || [], skills).map(x => ({ ...x, kind: "Project", href: `/projects/${x.id}` }))].sort((a, b) => score(b, skills) - score(a, skills) || +new Date(b.created_at) - +new Date(a.created_at)).slice(0, 4)
  return <main className="min-h-screen max-w-full overflow-x-clip bg-brand-ivory pb-24 lg:pb-16"><div className="mx-auto max-w-7xl px-4 py-8 sm:py-10"><header className="mb-7 min-w-0"><p className="text-caption font-bold tracking-[.16em] text-brand-coral">OPPORTUNITY HUB</p><h1 className="mt-2 text-h2 font-extrabold text-brand-midnight sm:text-h1">Welcome back, {first}.</h1><p className="mt-2 text-body-sm text-brand-slate sm:text-body-lg">Here&apos;s what&apos;s happening around your professional world.</p><form action="/explore" className="relative mt-6 w-full max-w-3xl"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-brand-indigo" /><input name="q" placeholder="Search people, jobs, projects, services..." className="w-full min-w-0 rounded-pill border-2 border-brand-indigo/20 bg-white py-3.5 pl-12 pr-24 text-body-sm shadow-elevated outline-none focus:border-brand-indigo" /><button className="absolute right-2 top-2 shrink-0 rounded-pill bg-brand-indigo px-4 py-1.5 text-body-sm font-bold text-white">Search</button></form></header>
  <div className="grid min-w-0 gap-8 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 space-y-10"><div className="grid grid-cols-1 gap-3 min-[360px]:grid-cols-2 sm:grid-cols-3">{[["Find work","/jobs",BriefcaseBusiness],["Find talent","/freelancers",Compass],["Offer a service","/gigs/new",Package],[canHire ? "Post a job" : "Post a project",canHire ? "/jobs/new" : "/projects/new",CirclePlus],["Create organization","/organizations/new",Building2]].map(([label, href, Icon]) => { const I = Icon as typeof Compass; return <Link key={label as string} href={href as string} className="flex min-w-0 w-full items-center gap-2 rounded-xl border border-brand-borderLight bg-white p-3 text-body-sm font-bold text-brand-midnight shadow-soft hover:border-brand-indigo/40"><I className="h-4 w-4 shrink-0 text-brand-coral" /><span className="min-w-0">{label as string}</span></Link> })}</div>
  <Section title="Opportunities for you" href="/explore?tab=jobs" label="View all opportunities"><p className="-mt-2 mb-4 text-body-sm text-brand-slate">{skills.length ? "Prioritized by your profile skills, then recency." : "Latest real opportunities across GigWay."}</p>{opportunities.length ? <div className="grid gap-4 md:grid-cols-2">{opportunities.map((o: any) => <Link key={`${o.kind}-${o.id}`} href={o.href} className="rounded-card border border-brand-borderLight bg-white p-5 shadow-soft transition hover:-translate-y-0.5 hover:shadow-elevated"><span className={`rounded-pill px-2 py-1 text-caption font-bold ${o.kind === "Job" ? "bg-brand-coral/10 text-brand-coral" : "bg-brand-indigo/10 text-brand-indigo"}`}>{o.kind}</span><h3 className="mt-3 font-bold text-brand-midnight">{o.title}</h3><p className="mt-1 text-body-sm text-brand-slate">{o.kind === "Job" ? [o.company_name, o.location].filter(Boolean).join(" · ") : o.category || "Open project"}</p>{o.skills_required?.length ? <div className="mt-3 flex flex-wrap gap-1">{o.skills_required.slice(0,3).map((s: string) => <span key={s} className="rounded-pill bg-brand-ivory px-2 py-1 text-caption text-brand-slate">{s}</span>)}</div> : null}</Link>)}</div> : <Empty text="New opportunities will appear here." href="/jobs" label="Browse jobs" />}</Section>
  <Section title="Latest jobs" href="/jobs" label="View all jobs"><div className="grid gap-3 md:grid-cols-2">{(jobs || []).slice(0,4).map(j => <Link key={j.id} href={`/jobs/${j.id}`} className="rounded-xl border border-brand-borderLight bg-white p-4 hover:border-brand-indigo/30"><h3 className="font-bold text-brand-midnight">{j.title}</h3><p className="mt-1 text-body-sm text-brand-slate">{[j.company_name,j.location].filter(Boolean).join(" · ")}</p></Link>)}</div></Section>
  <Section title="Projects to explore" href="/projects" label="Explore projects"><div className="grid gap-3 md:grid-cols-2">{(projects || []).slice(0,4).map(p => <Link key={p.id} href={`/projects/${p.id}`} className="rounded-xl border border-brand-borderLight bg-white p-4 hover:border-brand-indigo/30"><h3 className="font-bold text-brand-midnight">{p.title}</h3><p className="mt-1 text-body-sm text-brand-slate">{p.category || "Project"}{p.budget ? ` · ₹${p.budget.toLocaleString("en-IN")}` : ""}</p></Link>)}</div></Section>
  <Section title="Professionals to discover" href="/explore?tab=people" label="Discover people">{people?.length ? <div className="grid gap-3 sm:grid-cols-2">{people.map(p => <Link key={p.id} href={`/u/${p.username}`} className="flex gap-3 rounded-card border border-brand-borderLight bg-white p-4 shadow-soft"><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-full bg-brand-indigo/10 font-bold text-brand-indigo">{p.avatar_url ? <img src={p.avatar_url} alt="" className="h-full w-full object-cover" /> : p.full_name?.[0] || <UserRound className="h-4 w-4" />}</div><div className="min-w-0"><p className="flex items-center gap-1 truncate font-bold text-brand-midnight">{p.full_name}{p.is_verified && <CheckCircle2 className="h-3.5 w-3.5 text-brand-indigo" />}</p><p className="text-caption text-brand-slate">@{p.username}</p><p className="mt-1 line-clamp-1 text-caption text-brand-slate">{p.tagline || p.skills?.slice(0,2).join(" · ")}</p></div></Link>)}</div> : <Empty text="Professionals will appear here as they join." href="/explore?tab=people" label="Discover people" />}</Section>
  <Section title="Organizations to discover" href="/explore?tab=organizations" label="View organizations">{organizations?.length ? <div className="grid gap-3 sm:grid-cols-2">{organizations.map(o => <Link key={o.id} href={`/u/${o.username}`} className="flex gap-3 rounded-card border border-brand-borderLight bg-white p-4 shadow-soft"><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-brand-coral/10 text-brand-coral">{o.logo_url ? <img src={o.logo_url} alt="" className="h-full w-full object-cover" /> : <Building2 className="h-4 w-4" />}</div><div className="min-w-0"><p className="font-bold text-brand-midnight">{o.name}</p><p className="text-caption text-brand-slate">@{o.username}</p><p className="mt-1 line-clamp-1 text-caption text-brand-slate">{[o.industry,o.location].filter(Boolean).join(" · ") || o.tagline}</p></div></Link>)}</div> : <Empty text="Organizations will appear here as they join GigWay." href="/organizations/new" label="Create an organization" />}</Section>
  <Section title="Services you may need" href="/gigs" label="Explore services">{gigs?.length ? <div className="grid gap-3 sm:grid-cols-2">{gigs.map(g => <Link key={g.id} href={`/gigs/${g.id}`} className="flex gap-3 rounded-card border border-brand-borderLight bg-white p-3 shadow-soft"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-brand-indigo/10">{g.image_url && <img src={g.image_url} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0"><p className="truncate font-bold text-brand-midnight">{g.title}</p><p className="mt-1 text-caption text-brand-slate">From ₹{g.price.toLocaleString("en-IN")} · {g.delivery_days} days</p></div></Link>)}</div> : <Empty text="Services will appear here when available." href="/gigs" label="Explore services" />}</Section></div>
  <aside className="space-y-5"><section className="rounded-card border border-brand-borderLight bg-white p-5 shadow-soft"><h2 className="font-extrabold text-brand-midnight">Your activity</h2><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Link href="/messages" className="rounded-xl bg-brand-ivory p-3"><b className="block text-lg text-brand-midnight">{unread || 0}</b><span className="text-caption text-brand-slate">Unread</span></Link><Link href="/profile" className="rounded-xl bg-brand-ivory p-3"><b className="block text-lg text-brand-midnight">{applications || 0}</b><span className="text-caption text-brand-slate">Applications</span></Link><Link href="/profile" className="rounded-xl bg-brand-ivory p-3"><b className="block text-lg text-brand-midnight">{proposals || 0}</b><span className="text-caption text-brand-slate">Proposals</span></Link></div></section>{incomplete && <section className="rounded-card border border-brand-indigo/20 bg-brand-indigo/[.04] p-5"><h2 className="font-extrabold text-brand-midnight">Make your profile easier to discover.</h2><p className="mt-2 text-body-sm text-brand-slate">Add your photo, tagline, skills and location to strengthen your professional identity.</p><Link href="/profile/edit" className="mt-4 inline-block text-body-sm font-bold text-brand-indigo">Complete profile →</Link></section>}</aside></div></div></main>
}
