import { isCurrentProductCategory } from "@/lib/product-visibility";
import { loginForCurrent } from "@/lib/auth/server"
import Link from "next/link";
import { redirect } from "next/navigation";
import { BriefcaseBusiness, Building2, Mic, PackagePlus, Send, UserRound, Video } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function CreatePage({ searchParams }: { searchParams: Promise<{ organization?: string; personal?: string }> }) {
  const q = await searchParams, db = await createClient(), { data: { user } } = await db.auth.getUser();
  if (!user) redirect(await loginForCurrent("/create"));
  const [{ data: profile }, { data: memberships }] = await Promise.all([
    db.from("profiles").select("full_name,username,avatar_url").eq("id", user.id).maybeSingle(),
    db.from("organization_members").select("organization_id,organizations(id,name,username,logo_url,entity_type)").eq("profile_id", user.id).eq("status", "active").in("member_role", ["owner", "admin"]),
  ]);
  const entities = (memberships || []).map((m: any) => m.organizations).filter(Boolean), selected = entities.find((o: any) => o.id === q.organization), personal = !selected;
  const actor = personal ? { name: profile?.full_name || "Professional", sub: `@${profile?.username || ""} · Professional Profile`, image: profile?.avatar_url } : { name: selected.name, sub: selected.entity_type === "company" ? "Workplace / Company" : "Workplace", image: selected.logo_url };
  const jox = { href: "/social/vijox/create", label: "Jox", sub: "Share your voice in up to 27 seconds.", Icon: Mic }, glimps = { href: "/social/glimps/create", label: "GLIMPS", sub: "Share a short professional video.", Icon: Video };
  const options = (personal ? [{ href: "/social/create", label: "Share a GigThought", sub: "Share an idea, update, question, photo or video with your professional network.", example: "I'm a graphic designer available for new freelance projects.", Icon: Send }, jox, glimps, { href: "/jobs/new", label: "Post a Job", sub: "Hiring for a role? Post a job opening and find people who may be a good fit.", example: "Hiring a Sales Executive in Lucknow.", Icon: BriefcaseBusiness }, { href: "/projects/new", label: "Post a Project", sub: "Need a specific piece of work done? Post the project and let professionals respond.", example: "Need someone to build a business website.", Icon: Building2 }, { href: "/gigs/new", label: "Offer a Service", sub: "Show people what you can do and offer your skill as a professional service.", example: "Logo Design, Tuition, Legal Help, Photography.", Icon: PackagePlus }] : [{ href: `/social/create?organization=${selected.id}`, label: "Share a GigThought", sub: "Share an update as this entity.", Icon: Send }, jox, glimps, { href: `/jobs/new?organization=${selected.id}`, label: "Post a Job", sub: "Post a role as this entity.", Icon: BriefcaseBusiness }]).filter(item => isCurrentProductCategory(item.href.split("/")[2] || ""));
  return <main className="min-h-screen bg-brand-ivory px-4 py-8 pb-24"><div className="mx-auto max-w-2xl"><p className="text-caption font-bold tracking-[.16em] text-brand-coral">CREATE</p><h1 className="mt-2 text-h2 font-extrabold text-brand-midnight">{selected ? "Choose what to create" : "Create as"}</h1>{!selected && q.personal !== "1" && entities.length > 0 ? <div className="mt-6 space-y-3"><Link href="/create?personal=1" className="flex items-center gap-3 rounded-2xl border border-brand-indigo bg-white p-4"><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-full bg-brand-indigo/10 text-brand-indigo">{profile?.avatar_url ? <img src={profile.avatar_url} alt="" className="h-full w-full object-cover" /> : <UserRound className="h-5 w-5" />}</span><span><b className="block text-brand-midnight">{profile?.full_name || "Professional"}</b><span className="text-caption text-brand-slate">@{profile?.username} · Professional Profile</span></span></Link>{entities.map((o: any) => <Link key={o.id} href={`/create?organization=${o.id}`} className="flex items-center gap-3 rounded-2xl border border-brand-borderLight bg-white p-4"><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-xl bg-brand-indigo/10 text-brand-indigo">{o.logo_url ? <img src={o.logo_url} alt="" className="h-full w-full object-cover" /> : <Building2 className="h-5 w-5" />}</span><span><b className="block text-brand-midnight">{o.name}</b><span className="text-caption text-brand-slate">{o.entity_type === "company" ? "Workplace / Company" : "Workplace"}</span></span></Link>)}</div> : <><div className="mt-5 flex items-center gap-3 rounded-2xl border border-brand-borderLight bg-white p-4"><span className="grid h-10 w-10 place-items-center overflow-hidden rounded-xl bg-brand-indigo/10 text-brand-indigo">{actor.image ? <img src={actor.image} alt="" className="h-full w-full object-cover" /> : <UserRound className="h-5 w-5" />}</span><span className="min-w-0 flex-1"><span className="mb-1 block text-caption text-brand-slate">You are posting as</span><b className="block truncate text-brand-midnight">{actor.name}</b><span className="text-caption text-brand-slate">{actor.sub}</span></span>{selected && <Link href="/create" className="text-caption font-bold text-brand-indigo">Change</Link>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{options.map((option) => { const { href, label, sub, Icon } = option; return <Link key={label} href={href} className="min-w-0 break-words rounded-2xl border border-brand-borderLight bg-white p-5 shadow-soft hover:border-brand-indigo/40"><Icon className="h-5 w-5 text-brand-indigo" /><h2 className="mt-4 font-bold text-brand-midnight">{label}</h2><p className="mt-1 text-body-sm text-brand-slate">{sub}</p>{"example" in option && <p className="mt-3 text-caption leading-relaxed text-brand-slate/80">Example: &ldquo;{String(option.example)}&rdquo;</p>}</Link>})}</div></>}</div></main>;
}
