import Link from "next/link";
import { redirect } from "next/navigation";
import { BriefcaseBusiness, Building2, PackagePlus, Send, UserRound, Video } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function CreatePage({ searchParams }: { searchParams: Promise<{ organization?: string }> }) {
  const q = await searchParams, db = await createClient(), { data: { user } } = await db.auth.getUser();
  if (!user) redirect("/login?next=/create");
  const [{ data: profile }, { data: memberships }] = await Promise.all([
    db.from("profiles").select("full_name,username,avatar_url").eq("id", user.id).maybeSingle(),
    db.from("organization_members").select("organization_id,organizations(id,name,username,logo_url,entity_type)").eq("profile_id", user.id).eq("status", "active").in("member_role", ["owner", "admin"]),
  ]);
  const entities = (memberships || []).map((m: any) => m.organizations).filter(Boolean), selected = entities.find((o: any) => o.id === q.organization), personal = !selected;
  const actor = personal ? { name: profile?.full_name || "Professional", sub: `@${profile?.username || ""} · Professional`, image: profile?.avatar_url } : { name: selected.name, sub: selected.entity_type === "company" ? "Company" : "Organization", image: selected.logo_url };
  const glimps = { href: "/social/glimps/create", label: "GLIMPS", sub: "Share a short professional video.", Icon: Video };
  const options = personal ? [{ href: "/social/create", label: "Post", sub: "Share an update, photo, video or document.", Icon: Send }, glimps, { href: "/jobs/new", label: "Job", sub: "Hire for a role.", Icon: BriefcaseBusiness }, { href: "/projects/new", label: "Project", sub: "Post work for professionals.", Icon: Building2 }, { href: "/gigs/new", label: "Service", sub: "Offer your expertise as a service.", Icon: PackagePlus }] : [{ href: `/social/create?organization=${selected.id}`, label: "Post", sub: "Share an update as this entity.", Icon: Send }, glimps, { href: `/jobs/new?organization=${selected.id}`, label: "Job", sub: "Post a role as this entity.", Icon: BriefcaseBusiness }];
  return <main className="min-h-screen bg-brand-ivory px-4 py-8 pb-24"><div className="mx-auto max-w-2xl"><p className="text-caption font-bold tracking-[.16em] text-brand-coral">CREATE</p><h1 className="mt-2 text-h2 font-extrabold text-brand-midnight">{selected ? "Choose what to create" : "Create as"}</h1>{!selected && entities.length > 0 ? <div className="mt-6 space-y-3"><Link href="/create" className="flex items-center gap-3 rounded-2xl border border-brand-indigo bg-white p-4"><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-full bg-brand-indigo/10 text-brand-indigo">{profile?.avatar_url ? <img src={profile.avatar_url} alt="" className="h-full w-full object-cover" /> : <UserRound className="h-5 w-5" />}</span><span><b className="block text-brand-midnight">{profile?.full_name || "Professional"}</b><span className="text-caption text-brand-slate">@{profile?.username} · Professional</span></span></Link>{entities.map((o: any) => <Link key={o.id} href={`/create?organization=${o.id}`} className="flex items-center gap-3 rounded-2xl border border-brand-borderLight bg-white p-4"><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-xl bg-brand-indigo/10 text-brand-indigo">{o.logo_url ? <img src={o.logo_url} alt="" className="h-full w-full object-cover" /> : <Building2 className="h-5 w-5" />}</span><span><b className="block text-brand-midnight">{o.name}</b><span className="text-caption text-brand-slate">{o.entity_type === "company" ? "Company" : "Organization"}</span></span></Link>)}</div> : <><div className="mt-5 flex items-center gap-3 rounded-2xl border border-brand-borderLight bg-white p-4"><span className="grid h-10 w-10 place-items-center overflow-hidden rounded-xl bg-brand-indigo/10 text-brand-indigo">{actor.image ? <img src={actor.image} alt="" className="h-full w-full object-cover" /> : <UserRound className="h-5 w-5" />}</span><span className="min-w-0 flex-1"><b className="block truncate text-brand-midnight">Creating as {actor.name}</b><span className="text-caption text-brand-slate">{actor.sub}</span></span>{selected && <Link href="/create" className="text-caption font-bold text-brand-indigo">Change</Link>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{options.map(({ href, label, sub, Icon }) => <Link key={label} href={href} className="rounded-2xl border border-brand-borderLight bg-white p-5 shadow-soft hover:border-brand-indigo/40"><Icon className="h-5 w-5 text-brand-indigo" /><h2 className="mt-4 font-bold text-brand-midnight">{label}</h2><p className="mt-1 text-body-sm text-brand-slate">{sub}</p></Link>)}</div></>}</div></main>;
}
