import Link from "next/link";
import DiscoveryCards from "@/components/connections/DiscoveryCards";
import { networkDiscovery, type DiscoveryKind } from "@/lib/network/discovery";
import { workPreviews } from "@/lib/work/previews";
import ContentTimestamp from "@/components/ui/ContentTimestamp";

export async function PeoplePreview({ viewerId, kind }: { viewerId: string; kind: DiscoveryKind }) {
  const people = kind === "people";
  const items = await networkDiscovery(kind, viewerId, 6);
  return <section className="mt-7 min-w-0"><h2 className="text-h3 font-extrabold text-brand-midnight">{people ? "People for you" : "Workplaces to follow"}</h2><p className="mt-2 text-body-sm text-brand-slate">{people ? "Professionals you may want to connect with." : "Companies and organizations you may want to follow."}</p><DiscoveryCards items={items} kind={kind} rail /><Link prefetch={false} href={people ? "/network" : "/network?tab=workplaces"} className="mt-3 inline-block text-caption font-bold text-brand-indigo">View all {people ? "professionals" : "Workplaces"}</Link></section>;
}
export function FindWorkEntry() {
  return <section className="mt-7 rounded-2xl border border-brand-borderLight bg-white p-4"><h2 className="text-h3 font-extrabold text-brand-midnight">Find Work</h2><p className="mt-2 text-body-sm text-brand-slate">Search jobs, projects and services.</p><Link prefetch={false} href="/work" className="mt-4 block rounded-xl border border-brand-indigo/25 px-4 py-3 text-body-sm font-bold text-brand-indigo">Explore work opportunities</Link><div className="mt-3 flex flex-wrap gap-4">{[["Jobs", "/jobs"], ["Projects", "/projects"], ["Services", "/gigs"]].map(([label, href]) => <Link prefetch={false} key={href} href={href} className="text-caption font-bold text-brand-indigo">{label}</Link>)}</div></section>;
}
export async function LatestOpportunities() {
  const kinds = ["jobs", "projects", "services"] as const;
  const results = await Promise.all(kinds.map(kind => workPreviews(kind, 2)));
  const items = results.flatMap((result, index) => result.items.map(item => ({ ...item, kind: kinds[index] })));
  return <section className="mt-7 min-w-0"><h2 className="text-h3 font-extrabold text-brand-midnight">Latest Opportunities</h2><p className="mt-2 text-body-sm text-brand-slate">Recent work opportunities on GigWay.</p>{results.some(result => result.unavailable) && <p role="status" className="mt-3 text-caption text-brand-slate">Some opportunities could not be loaded. Browse Work to try again.</p>}{!items.length ? <p className="mt-4 text-body-sm text-brand-slate">{results.some(result => result.unavailable) ? "Opportunities are temporarily unavailable." : "No work opportunities available yet."}</p> : <div role="region" aria-label="Latest Opportunities" tabIndex={0} className="mt-4 flex max-w-full snap-x gap-3 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{items.map(item => <article key={`${item.kind}:${item.id}`} className="flex w-[85%] min-w-0 shrink-0 snap-start flex-col rounded-2xl border border-brand-borderLight bg-white p-4 shadow-soft sm:w-64"><p className="text-caption font-bold text-brand-indigo">{item.kind === "jobs" ? "Job" : item.kind === "projects" ? "Project" : "Service"}</p><h3 className="mt-2 break-words font-bold text-brand-midnight">{item.title}</h3>{item.author && <p className="mt-2 break-words text-body-sm text-brand-slate">{item.author}</p>}{item.detail && <p className="mt-2 break-words text-caption text-brand-slate">{item.detail}</p>}{item.amount != null && Number.isFinite(Number(item.amount)) && <p className="mt-2 text-body-sm text-brand-indigo">{item.kind === "services" ? "From " : "Budget: "}₹{Number(item.amount).toLocaleString("en-IN")}</p>}<ContentTimestamp createdAt={item.createdAt} updatedAt={item.updatedAt} className="mt-3 block text-caption text-brand-slate" /><Link prefetch={false} href={`/${item.kind === "services" ? "gigs" : item.kind}/${item.id}`} className="mt-auto pt-4 text-caption font-bold text-brand-indigo">View {item.kind === "jobs" ? "Job" : item.kind === "projects" ? "Project" : "Service"}</Link></article>)}</div>}<Link prefetch={false} href="/work" className="mt-3 inline-block text-caption font-bold text-brand-indigo">View all opportunities</Link></section>;
}
