"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Sparkles, X } from "lucide-react";
import type { Moment } from "@/lib/moments";

export function RakhiMotif() { return <span aria-hidden className="moment-rakhi ml-1 inline-flex h-6 w-6 items-center justify-center rounded-full border border-brand-coral/35 bg-brand-coral/10 text-[11px] font-extrabold text-brand-coral">R</span>; }
export function MomentHeader({ moment }: { moment: Moment | null }) { const [open, setOpen] = useState(false); if (!moment) return null; return <span className="relative"><button onClick={() => setOpen(value => !value)} aria-expanded={open} aria-label={`Open ${moment.name} moment`} className="rounded-full outline-none focus-visible:ring-2 focus-visible:ring-brand-indigo"><RakhiMotif /></button>{open && <div className="absolute left-0 top-9 z-[60] w-72 rounded-2xl border border-brand-borderLight bg-white p-4 shadow-elevated"><button onClick={() => setOpen(false)} aria-label="Close moment" className="absolute right-2 top-2 rounded-full p-1 text-brand-slate hover:bg-brand-ivory"><X className="h-4 w-4" /></button><p className="text-caption font-bold tracking-[.12em] text-brand-coral">GIGWAY MOMENT</p><h2 className="mt-1 font-extrabold text-brand-midnight">{moment.title}</h2><p className="mt-1 text-body-sm text-brand-slate">{moment.message}</p><p className="mt-3 text-body-sm font-bold text-brand-midnight">{moment.conversationPrompt}</p><div className="mt-4 grid gap-2"><Link onClick={() => setOpen(false)} href={moment.primaryCTA.href} className="rounded-xl bg-brand-indigo px-3 py-2 text-center text-caption font-bold text-white">{moment.primaryCTA.label}</Link><Link onClick={() => setOpen(false)} href={moment.secondaryCTA.href} className="rounded-xl border border-brand-indigo/25 px-3 py-2 text-center text-caption font-bold text-brand-indigo">{moment.secondaryCTA.label}</Link></div></div>}</span>; }
export function MomentHomeCard({ moment }: { moment: Moment | null }) { const [dismissed, setDismissed] = useState(true); useEffect(() => { setDismissed(!moment || localStorage.getItem(`gigway:moment:dismissed:${moment.slug}`) === "1"); }, [moment]); if (!moment || dismissed) return null; return <section className="mb-5 rounded-2xl border border-brand-coral/20 bg-white p-4 shadow-soft"><div className="flex gap-3"><span aria-hidden className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-coral/10 text-brand-coral"><Sparkles className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-caption font-bold tracking-[.13em] text-brand-coral">TODAY ON GIGWAY</p><h2 className="mt-1 font-extrabold text-brand-midnight">{moment.name}</h2></div><button onClick={() => { localStorage.setItem(`gigway:moment:dismissed:${moment.slug}`, "1"); setDismissed(true); }} aria-label="Dismiss moment" className="rounded-full p-1 text-brand-slate hover:bg-brand-ivory"><X className="h-4 w-4" /></button></div><p className="mt-2 text-body-sm font-semibold text-brand-midnight">{moment.conversationPrompt}</p><div className="mt-3 flex flex-wrap gap-2"><Link href={moment.primaryCTA.href} className="rounded-xl bg-brand-indigo px-3 py-2 text-caption font-bold text-white">{moment.primaryCTA.label}</Link><Link href={moment.secondaryCTA.href} className="rounded-xl border border-brand-indigo/25 px-3 py-2 text-caption font-bold text-brand-indigo">Record VIJOX</Link></div></div></div></section>; }
