"use client"

import { useRef, useState } from "react"
import { Camera, ImagePlus, Loader2, Trash2 } from "lucide-react"
import { createClient } from "@/lib/supabase/client"

export function ImageUploader({ value, onChange, kind = "avatar", label, maxMb = 5 }: { value?: string; onChange: (url: string) => void; kind?: "avatar" | "cover" | "logo"; label: string; maxMb?: number }) {
  const ref = useRef<HTMLInputElement>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const supabase = createClient()
  const cover = kind === "cover"
  const upload = async (file?: File) => { if (!file) return; if (!file.type.startsWith("image/") || file.size > maxMb * 1024 * 1024) { setError(`Choose a JPG, PNG, or WebP under ${maxMb}MB.`); return }; setLoading(true); setError(""); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Please sign in before uploading."); setLoading(false); return }; const ext = file.name.split(".").pop() || "jpg"; const path = `${user.id}/${kind}s/${Date.now()}.${ext}`; const { error: uploadError } = await supabase.storage.from("avatars").upload(path, file, { upsert: false }); if (uploadError) { setError("We couldn’t upload that image. Please try again."); setLoading(false); return }; const { data } = supabase.storage.from("avatars").getPublicUrl(path); onChange(data.publicUrl); setLoading(false) }
  return <div className="space-y-2"><input ref={ref} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e => upload(e.target.files?.[0])} />{cover ? <div className="relative h-32 overflow-hidden rounded-2xl bg-gradient-to-br from-[#302b63] via-[#24243e] to-[#F97316]/40">{value && <img src={value} alt="Cover preview" className="h-full w-full object-cover" />}<button type="button" onClick={() => ref.current?.click()} className="absolute inset-0 grid place-items-center bg-black/25 text-sm font-semibold text-white opacity-100 transition hover:bg-black/45"><span className="flex items-center gap-2"><ImagePlus className="h-4 w-4" />{loading ? "Uploading…" : value ? "Change cover" : label}</span></button></div> : <div className="flex items-center gap-4"><button type="button" onClick={() => ref.current?.click()} className="relative grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#1d1d29] text-[#B9B3FF] ring-1 ring-white/10 hover:ring-[#8177f7]">{value ? <img src={value} alt="Image preview" className="h-full w-full object-cover" /> : <Camera className="h-6 w-6" />}{loading && <span className="absolute inset-0 grid place-items-center bg-black/50"><Loader2 className="h-5 w-5 animate-spin text-white" /></span>}</button><div><button type="button" onClick={() => ref.current?.click()} className="text-sm font-semibold text-white hover:text-[#B9B3FF]">{value ? "Change image" : label}</button><p className="mt-1 text-xs text-[#858da0]">JPG, PNG or WebP · max {maxMb}MB</p>{value && <button type="button" onClick={() => onChange("")} className="mt-2 flex items-center gap-1 text-xs text-[#FB923C]"><Trash2 className="h-3 w-3" /> Remove</button>}</div></div>}{error && <p className="text-xs text-red-400">{error}</p>}</div>
}
