"use client";
import { Camera, FlipHorizontal, Square, Video, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { GLIMPS_VIDEO_MIME_TYPES } from "@/lib/social/content-domain";

const stamp = (n: number) => `00:${Math.floor(n).toString().padStart(2, "0")}`;
export default function GlimpsCameraCapture({ onVideo, onCaptureStateChange }: { onVideo: (file: File) => void; onCaptureStateChange?: (open: boolean) => void }) {
  const live = useRef<HTMLVideoElement>(null), stream = useRef<MediaStream | null>(null), recorder = useRef<MediaRecorder | null>(null), timer = useRef<ReturnType<typeof setInterval> | null>(null), stopAt = useRef<ReturnType<typeof setTimeout> | null>(null), chunks = useRef<Blob[]>([]), request = useRef(0);
  const [open, setOpen] = useState(false), [recording, setRecording] = useState(false), [seconds, setSeconds] = useState(0), [facing, setFacing] = useState<"user" | "environment">("user"), [error, setError] = useState(""), [streamTick, setStreamTick] = useState(0);
  const cleanup = () => { if (timer.current) clearInterval(timer.current); if (stopAt.current) clearTimeout(stopAt.current); timer.current = null; stopAt.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; if (live.current) live.current.srcObject = null; };
  useEffect(() => () => cleanup(), []);
  useEffect(() => { const player = live.current; if (!player || !stream.current) return; player.srcObject = stream.current; const play = () => { void player.play().catch(() => undefined); }; player.onloadedmetadata = play; player.oncanplay = play; play(); return () => { player.onloadedmetadata = null; player.oncanplay = null; }; }, [open, streamTick]);
  const mime = () => ["video/webm;codecs=vp9,opus", "video/webm;codecs=vp8,opus", "video/webm", "video/mp4"].find(value => GLIMPS_VIDEO_MIME_TYPES.includes(value.split(";")[0] as any) && typeof MediaRecorder !== "undefined" && MediaRecorder.isTypeSupported(value));
  const startCamera = async (next = facing) => { const version = ++request.current; setError(""); setOpen(true); onCaptureStateChange?.(true); if (!navigator.mediaDevices?.getUserMedia) return setError("Camera isn't available on this browser. Upload a video instead."); if (typeof MediaRecorder === "undefined" || !mime()) return setError("Camera recording isn't supported on this browser. Upload a video instead."); cleanup(); const constraints = { video: { facingMode: { ideal: next }, aspectRatio: { ideal: 9 / 16 }, width: { ideal: 720 }, height: { ideal: 1280 } }, audio: true }; try { let value: MediaStream; try { value = await navigator.mediaDevices.getUserMedia(constraints); } catch { value = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); } if (version !== request.current) { value.getTracks().forEach(track => track.stop()); return; } stream.current = value; setFacing(next); setStreamTick(tick => tick + 1); } catch { if (version === request.current) setError("We couldn't access your camera and microphone. Check permissions, then try again."); } };
  const stopRecording = () => { if (recorder.current?.state === "recording") recorder.current.stop(); };
  const record = () => { const type = mime(); if (!stream.current || !type || recording) return; chunks.current = []; const value = new MediaRecorder(stream.current, { mimeType: type }); recorder.current = value; value.ondataavailable = event => { if (event.data.size) chunks.current.push(event.data); }; value.onerror = () => { setError("Recording failed. Please try again."); cleanup(); setRecording(false); }; value.onstop = () => { const actual = value.mimeType || type, blob = new Blob(chunks.current, { type: actual }), extension = actual.startsWith("video/mp4") ? "mp4" : "webm"; cleanup(); setRecording(false); setOpen(false); onCaptureStateChange?.(false); onVideo(new File([blob], `glimps-recording-${Date.now()}.${extension}`, { type: actual })); }; value.start(); setSeconds(0); setRecording(true); timer.current = setInterval(() => setSeconds(value => value + 1), 1000); stopAt.current = setTimeout(stopRecording, 60000); };
  if (!open) return <button type="button" onClick={() => void startCamera()} className="flex min-h-40 w-full flex-col items-center justify-center rounded-3xl border border-brand-indigo/25 bg-brand-indigo/[.04] p-4 text-center"><span className="grid h-12 w-12 place-items-center rounded-full bg-brand-indigo text-white"><Camera /></span><b className="mt-3">Camera</b><span className="mt-1 text-caption leading-4 text-brand-slate">Record in portrait</span></button>;
  return <div className="mt-5 overflow-hidden rounded-[2rem] bg-brand-midnight p-3 text-white shadow-2xl"><video ref={live} playsInline muted className="aspect-[9/16] min-h-[26rem] max-h-[65dvh] w-full rounded-[1.4rem] bg-black object-cover" />{error && <p className="mt-2 text-caption text-red-200">{error}</p>}<div className="mt-3 flex items-center justify-between gap-2"><span className="font-bold tabular-nums">{stamp(seconds)} / 01:00</span><div className="flex gap-2"><button type="button" onClick={() => void startCamera(facing === "user" ? "environment" : "user")} disabled={recording} className="grid h-11 w-11 place-items-center rounded-full border border-white/30" aria-label="Flip Camera"><FlipHorizontal className="h-5 w-5" /></button><button type="button" onClick={recording ? stopRecording : record} className="grid h-14 w-14 place-items-center rounded-full bg-brand-coral ring-4 ring-white/20" aria-label={recording ? "Stop recording" : "Start recording"}>{recording ? <Square className="h-5 w-5 fill-current" /> : <Video className="h-6 w-6" />}</button><button type="button" onClick={() => { ++request.current; stopRecording(); cleanup(); setOpen(false); onCaptureStateChange?.(false); }} className="grid h-11 w-11 place-items-center rounded-full border border-white/30" aria-label="Cancel camera"><X className="h-5 w-5" /></button></div></div></div>;
}
