"use client";

import Link from "next/link";
import { Bookmark, Heart, Loader2, MessageSquare, Pause, Play, Repeat2, Send, Volume2, VolumeX } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { Post } from "@/components/social/SocialHomeFeed";
import { announceMediaPlay, MEDIA_PLAY_EVENT } from "@/lib/social/media-playback";

type Props = { post: Post; authHref?: string; isActive?: boolean; autoPlayWhenActive?: boolean; muted?: boolean; onMutedChange?: (muted: boolean) => void; onRefresh: () => void; onComments?: () => void; onUserPlaybackChange?: (playing: boolean) => void; onMediaRefresh?: (post: Post) => void };
const clock = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${Math.floor(seconds % 60).toString().padStart(2, "0")}`;

export default function GlimpsExperience({ post, authHref, isActive = true, autoPlayWhenActive = false, muted: controlledMuted, onMutedChange, onRefresh, onComments, onUserPlaybackChange, onMediaRefresh }: Props) {
  const media = post.media.find((item) => item.type === "video"), video = useRef<HTMLVideoElement>(null), recovery = useRef(false);
  const [source, setSource] = useState(media?.url || ""), [playing, setPlaying] = useState(false), [loading, setLoading] = useState(true), [failed, setFailed] = useState(false), [current, setCurrent] = useState(0), [duration, setDuration] = useState(media?.durationSeconds || 0), [localMuted, setLocalMuted] = useState(controlledMuted ?? false), [expanded, setExpanded] = useState(false), [liked, setLiked] = useState(post.isLikedByMe), [saved, setSaved] = useState(post.isSavedByMe), [reposted, setReposted] = useState(post.isRepostedByMe), [repostCount, setRepostCount] = useState(post.repostCount), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const muted = controlledMuted ?? localMuted, caption = post.body || "", longCaption = caption.length > 180;
  const setMuted = (value: boolean) => { if (controlledMuted === undefined) setLocalMuted(value); onMutedChange?.(value); };
  useEffect(() => { setSource(media?.url || ""); recovery.current=false; setFailed(false); }, [media?.url]);
  const recover = async (manual=false) => { if (manual) recovery.current=false; if (recovery.current || post.visibility !== "followers") return false; recovery.current=true; try { const response=await fetch(`/api/social/posts/${post.id}`), data=await response.json(); const refreshed=data?.post as Post | undefined, next=refreshed?.media.find((item)=>item.type==="video"); if(!response.ok||!refreshed||!next?.url) throw Error(); onMediaRefresh?.(refreshed); setSource(next.url); setFailed(false); setLoading(true); return true; } catch { return false; } };
  const retry = async () => { setFailed(false); setLoading(true); if (post.visibility === "followers") { const refreshed=await recover(true); if (!refreshed) { setFailed(true); setLoading(false); } return; } video.current?.load(); };
  useEffect(() => { const pauseOther = (event: Event) => { if ((event as CustomEvent<string>).detail !== post.id) video.current?.pause(); }; window.addEventListener(MEDIA_PLAY_EVENT, pauseOther); return () => window.removeEventListener(MEDIA_PLAY_EVENT, pauseOther); }, [post.id]);
  useEffect(() => { if (!isActive || !autoPlayWhenActive) { video.current?.pause(); return; } if (video.current?.paused) { video.current.muted = muted; announceMediaPlay(post.id); video.current.play().catch(() => undefined); } }, [isActive, autoPlayWhenActive, muted, post.id]);
  const auth = () => { if (!authHref) return false; location.assign(authHref); return true; };
  const toggle = async () => { if (failed || !video.current) return; if (video.current.paused) { if (video.current.ended) video.current.currentTime = 0; announceMediaPlay(post.id); try { await video.current.play(); onUserPlaybackChange?.(true); } catch { setFailed(true); } } else { video.current.pause(); onUserPlaybackChange?.(false); } };
  const request = async (path: string, method = "POST") => { const response = await fetch(path, { method }); const data = await response.json().catch(() => ({})); if (!response.ok) throw Error(data.error || "Action failed."); return data; };
  const action = async (kind: "like" | "save") => { if (auth()) return; const value = kind === "like" ? liked : saved; try { setBusy(true); const data = await request(`/api/social/posts/${post.id}/${kind}`, value ? "DELETE" : "POST"); if (kind === "like") setLiked(!value); else setSaved(data.saved === true); onRefresh(); } catch { setNotice("Could not update this GLIMPS."); } finally { setBusy(false); } };
  const repost = async () => { if (auth() || !post.canRepost) return; const previous = reposted; setReposted(!previous); setRepostCount((count) => Math.max(0, count + (previous ? -1 : 1))); try { await request(`/api/social/posts/${post.id}/repost`, previous ? "DELETE" : "POST"); onRefresh(); } catch { setReposted(previous); setRepostCount((count) => Math.max(0, count + (previous ? 1 : -1))); setNotice("Could not update repost."); } };
  const follow = async () => { if (auth() || !post.author) return; try { await request(`/api/social/follow/${post.author.type === "organization" ? "organization" : "profile"}/${post.author.id}`, post.isFollowing ? "DELETE" : "POST"); onRefresh(); } catch { setNotice("Could not update follow."); } };
  const share = async () => { const url = `https://gigway.in/social/posts/${post.id}`; try { if (navigator.share) { await navigator.share({ title: `${post.author?.name || "GigWay member"} on GigWay`, text: caption.slice(0, 180) || "View this GLIMPS on GigWay.", url }); return; } await navigator.clipboard.writeText(url); setNotice("Link copied"); } catch {} };
  if (!media) return null;
  const authorHref = post.author?.username ? `/u/${post.author.username}` : null, portrait = !!media.width && !!media.height && media.height >= media.width;
  return <article className="overflow-hidden rounded-3xl border border-brand-borderLight bg-white shadow-elevated"><div className={`relative mx-auto overflow-hidden bg-gradient-to-br from-brand-midnight via-brand-indigoDark to-brand-midnight ${portrait ? "max-w-[31rem] aspect-[9/16]" : "aspect-video max-w-3xl"}`}>
    <video ref={video} src={source} preload="metadata" playsInline muted={muted} className="h-full w-full object-contain" aria-label={`GLIMPS video: ${media.fileName}`} onLoadedMetadata={() => { setDuration(video.current?.duration || media.durationSeconds || 0); setLoading(false); }} onCanPlay={() => setLoading(false)} onWaiting={() => setLoading(true)} onPlaying={() => { setPlaying(true); setLoading(false); }} onPause={() => setPlaying(false)} onTimeUpdate={() => setCurrent(video.current?.currentTime || 0)} onEnded={() => setPlaying(false)} onError={() => { void recover().then((ok) => { if (!ok) { setFailed(true); setLoading(false); } }); }} />
    {loading && !failed && <div className="absolute inset-0 animate-pulse bg-gradient-to-br from-brand-indigo/25 via-brand-midnight/45 to-brand-coral/15" aria-label="Loading GLIMPS" />}
    {failed ? <div className="absolute inset-0 grid place-items-center bg-brand-midnight/80 p-6 text-center text-body-sm font-bold text-white"><div>This GLIMPS couldn’t be played.<button type="button" onClick={() => void retry()} aria-label="Retry GLIMPS playback" className="mx-auto mt-3 block min-h-10 rounded-lg border border-white/60 px-4 py-2 text-caption font-bold focus-visible:ring-2 focus-visible:ring-white">Retry</button></div></div> : <><button type="button" onClick={toggle} className="absolute inset-0 z-10 grid place-items-center outline-none focus-visible:ring-4 focus-visible:ring-white/80" aria-label={playing ? "Pause GLIMPS" : "Play GLIMPS"}>{!playing && !loading && <span className="grid h-14 w-14 place-items-center rounded-full bg-white/95 text-brand-indigo shadow-elevated"><Play className="ml-0.5 h-6 w-6 fill-current" /></span>}</button><div className="absolute inset-x-0 bottom-0 z-20 bg-gradient-to-t from-black/80 via-black/35 to-transparent px-4 pb-4 pt-14 text-white"><input aria-label="GLIMPS progress" type="range" min="0" max={duration || 1} step="0.1" value={Math.min(current, duration || 1)} onChange={(event) => { if (video.current) video.current.currentTime = Number(event.target.value); setCurrent(Number(event.target.value)); }} className="mb-2 block w-full accent-brand-coral" /><div className="flex items-center gap-2"><button type="button" onClick={toggle} aria-label={playing ? "Pause GLIMPS" : "Play GLIMPS"} className="rounded-full p-2 hover:bg-white/15">{playing ? <Pause className="h-4 w-4 fill-current" /> : <Play className="h-4 w-4 fill-current" />}</button><span className="text-caption font-bold tabular-nums">{clock(current)} / {clock(duration)}</span><span className="flex-1" /><button type="button" onClick={() => setMuted(!muted)} aria-label={muted ? "Unmute GLIMPS" : "Mute GLIMPS"} className="rounded-full p-2 hover:bg-white/15">{muted ? <VolumeX className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />}</button></div></div></>}
    <p className="absolute left-4 top-4 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-extrabold tracking-[.14em] text-brand-indigo">GLIMPS</p>
  </div><div className="p-4 sm:p-5"><div className="flex gap-3"><Link href={authorHref || "#"} aria-label={`View ${post.author?.name || "creator"}`} className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full bg-brand-indigo/10 font-bold text-brand-indigo">{post.author?.avatar ? <img src={post.author.avatar} alt="" className="h-full w-full object-cover" /> : post.author?.name?.[0] || "G"}</Link><div className="min-w-0 flex-1"><p className="truncate font-extrabold text-brand-midnight">{post.author?.name || "GigWay member"}</p><p className="truncate text-caption text-brand-slate">{post.author?.username ? `@${post.author.username}` : post.author?.type === "organization" ? "Organization" : "Professional"}</p></div>{post.canFollow && <button type="button" onClick={follow} className="min-h-10 rounded-xl border border-brand-indigo/25 px-3 text-caption font-bold text-brand-indigo">{post.isFollowing ? "Following" : "Follow"}</button>}</div>{caption && <div className="mt-4 text-body-sm leading-6 text-brand-midnight"><p className="whitespace-pre-wrap break-words">{expanded || !longCaption ? caption : `${caption.slice(0, 180)}…`}</p>{longCaption && <button type="button" onClick={() => setExpanded((value) => !value)} className="mt-1 text-caption font-bold text-brand-indigo">{expanded ? "Show less" : "more"}</button>}</div>}<div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-brand-borderLight pt-3 text-caption font-bold text-brand-slate"><button type="button" disabled={busy} onClick={() => action("like")} className={liked ? "text-brand-coral" : ""} aria-label={liked ? "Unlike GLIMPS" : "Like GLIMPS"}><Heart className={`mr-1 inline h-4 w-4 ${liked ? "fill-current" : ""}`} />{post.likeCount}</button><button type="button" onClick={() => auth() || onComments?.()}><MessageSquare className="mr-1 inline h-4 w-4" />{post.commentCount || "Comment"}</button><button type="button" disabled={!post.canRepost} onClick={repost} className={reposted ? "text-brand-indigo" : ""}><Repeat2 className="mr-1 inline h-4 w-4" />{repostCount || "Repost"}</button><button type="button" onClick={share}><Send className="mr-1 inline h-4 w-4" />Share</button><button type="button" disabled={busy} onClick={() => action("save")} aria-label={saved ? "Unsave GLIMPS" : "Save GLIMPS"} className={`ml-auto ${saved ? "text-brand-indigo" : ""}`}><Bookmark className={`h-4 w-4 ${saved ? "fill-current" : ""}`} /></button></div>{notice && <p className="mt-3 text-caption text-brand-coral" role="status">{notice}</p>}</div></article>;
}
