"use client";

import { Loader2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Post } from "@/components/social/SocialHomeFeed";
import GlimpsExperience from "@/components/social/GlimpsExperience";

type Props = { initialItems: Post[]; initialCursor: string | null; authHref?: string; initialActiveId?: string };
const interactive = (element: EventTarget | null) => element instanceof HTMLElement && !!element.closest("button,input,textarea,select,a,[contenteditable='true']");

export default function GlimpsFeed({ initialItems, initialCursor, authHref, initialActiveId }: Props) {
  const router = useRouter(), container = useRef<HTMLDivElement>(null), nodes = useRef(new Map<string, HTMLElement>()), loading = useRef(false);
  const [items, setItems] = useState(initialItems), [cursor, setCursor] = useState(initialCursor), [activeId, setActiveId] = useState(initialActiveId || initialItems[0]?.id || ""), [muted, setMuted] = useState(true), [manualPause, setManualPause] = useState<string | null>(null), [loadingMore, setLoadingMore] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (initialActiveId) requestAnimationFrame(() => nodes.current.get(initialActiveId)?.scrollIntoView({ block: "start" })); }, [initialActiveId]);
  const loadMore = async () => { if (!cursor || loading.current) return; loading.current = true; setLoadingMore(true); setError(""); try { const response = await fetch(`/api/social/glimps?cursor=${encodeURIComponent(cursor)}`), data = await response.json(); if (!response.ok) throw Error(); setItems((current) => [...current, ...(data.items || []).filter((item: Post) => !current.some((existing) => existing.id === item.id))]); setCursor(data.nextCursor || null); } catch { setError("Could not load more GLIMPS."); } finally { loading.current = false; setLoadingMore(false); } };
  useEffect(() => { const observer = new IntersectionObserver((entries) => { const candidates = entries.filter((entry) => entry.isIntersecting && entry.intersectionRatio >= .65).sort((a,b) => b.intersectionRatio-a.intersectionRatio); if (candidates[0]) { const id = (candidates[0].target as HTMLElement).dataset.postId; if (id) setActiveId((current) => current === id ? current : id); } }, { root: container.current, threshold: [.65, .8, 1] }); nodes.current.forEach((node) => observer.observe(node)); return () => observer.disconnect(); }, [items]);
  useEffect(() => { const onVisibility = () => { if (document.hidden) setManualPause(activeId); }; document.addEventListener("visibilitychange", onVisibility); return () => document.removeEventListener("visibilitychange", onVisibility); }, [activeId]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (interactive(event.target)) return; const index = items.findIndex((item) => item.id === activeId); if (event.key === " " && activeId) { event.preventDefault(); setManualPause((value) => value === activeId ? null : activeId); return; } const direction = event.key === "ArrowDown" || event.key === "PageDown" ? 1 : event.key === "ArrowUp" || event.key === "PageUp" ? -1 : 0; if (!direction || index < 0) return; event.preventDefault(); nodes.current.get(items[Math.max(0, Math.min(items.length - 1, index + direction))].id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [activeId, items]);
  useEffect(() => { const index = items.findIndex((item) => item.id === activeId); if (index >= items.length - 2) void loadMore(); }, [activeId, items.length]);
  if (!items.length) return <section className="mx-auto grid min-h-[60dvh] max-w-lg place-items-center px-4 text-center"><div><p className="text-caption font-bold tracking-[.15em] text-brand-coral">GLIMPS</p><h1 className="mt-2 text-h2 font-extrabold text-brand-midnight">No GLIMPS yet.</h1><p className="mt-2 text-body-sm text-brand-slate">Share a short professional video with your network.</p>{authHref === undefined && <button onClick={() => router.push("/social/glimps/create")} className="mt-5 rounded-xl bg-brand-indigo px-4 py-3 font-bold text-white">Create a GLIMPS</button>}</div></section>;
  return <div ref={container} role="feed" aria-label="GLIMPS feed" className="h-[calc(100dvh-4rem)] snap-y snap-mandatory overflow-y-auto overscroll-contain bg-brand-midnight sm:bg-gradient-to-br sm:from-brand-ivory sm:via-brand-slate/15 sm:to-brand-ivory" onScroll={() => { const node = nodes.current.get(activeId); if (node && node.getBoundingClientRect().bottom < window.innerHeight * .35) void loadMore(); }}>
    {items.map((post) => <section key={post.id} data-post-id={post.id} ref={(node) => { if (node) nodes.current.set(post.id, node); else nodes.current.delete(post.id); }} role="article" aria-label={`GLIMPS by ${post.author?.name || "GigWay member"}`} className="h-[calc(100dvh-4rem)] snap-start sm:flex sm:items-center sm:justify-center sm:px-6 sm:py-4"><GlimpsExperience immersive post={post} authHref={authHref} isActive={post.id === activeId} autoPlayWhenActive={post.id === activeId && manualPause !== post.id} muted={muted} onMutedChange={setMuted} onRefresh={() => router.refresh()} onComments={() => router.push(`/social/posts/${post.id}`)} onUserPlaybackChange={(playing) => setManualPause(playing ? null : post.id)} onMediaRefresh={(refreshed) => setItems((current) => current.map((item) => item.id === refreshed.id ? { ...item, media: refreshed.media } : item))} /></section>)}
    <div className="grid min-h-16 place-items-center text-caption text-brand-slate">{loadingMore && <Loader2 className="h-5 w-5 animate-spin text-brand-indigo" />}{error && <button onClick={() => void loadMore()} className="font-bold text-brand-indigo">Retry loading GLIMPS</button>}{!cursor && !loadingMore && <span>You're all caught up.</span>}</div>
  </div>;
}
