"use client";
import Link from "next/link";
import { Play } from "lucide-react";
import type { Post } from "@/components/social/SocialHomeFeed";

export default function GlimpsRail({ items }: { items: Post[] }) {
  if (!items.length) return null;
  return <section className="mt-6 min-w-0 border-b border-brand-borderLight/70 pb-5"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-extrabold tracking-[.16em] text-brand-coral">GLIMPS</p><h2 className="mt-0.5 font-extrabold text-brand-midnight">Quick professional moments</h2></div><Link href="/social/glimps" className="text-caption font-bold text-brand-indigo">See all →</Link></div><div className="-mx-4 flex snap-x gap-3 overflow-x-auto px-4 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mx-0 sm:px-0">{items.map((post) => { const video=post.media.find((media)=>media.type==="video"); return <Link key={post.id} href={`/social/glimps?post=${encodeURIComponent(post.id)}`} className="relative w-[104px] shrink-0 snap-start overflow-hidden rounded-xl bg-brand-midnight focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-indigo"><div className="aspect-[9/16] bg-gradient-to-br from-brand-indigo/75 via-brand-midnight to-brand-coral/50">{post.author?.avatar&&<img src={post.author.avatar} alt="" className="h-full w-full object-cover opacity-35"/>}<span className="absolute inset-0 grid place-items-center"><span className="grid h-8 w-8 place-items-center rounded-full bg-white/90 text-brand-indigo"><Play className="ml-px h-4 w-4 fill-current"/></span></span></div><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent px-2 pb-2 pt-7 text-white"><p className="truncate text-[10px] font-bold">{post.author?.name||"GigWay member"}</p>{video?.durationSeconds?<p className="text-[9px] text-white/75">{Math.round(video.durationSeconds)}s</p>:null}</div></Link>})}</div></section>;
}
