"use client";
import { Camera, FlipHorizontal, Square, Video, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { GLIMPS_VIDEO_MIME_TYPES } from "@/lib/social/content-domain";

const stamp = (n: number) => `00:${Math.floor(n).toString().padStart(2, "0")}`;
export default function GlimpsCameraCapture({ onVideo, onCaptureStateChange }: { onVideo: (file: File) => void; onCaptureStateChange?: (open: boolean) => void }) {
  const live = useRef<HTMLVideoElement>(null), stream = useRef<MediaStream | null>(null), recorder = useRef<MediaRecorder | null>(null), timer = useRef<ReturnType<typeof setInterval> | null>(null), stopAt = useRef<ReturnType<typeof setTimeout> | null>(null), chunks = useRef<Blob[]>([]), request = useRef(0), discardRecording = useRef(false);
  const [open, setOpen] = useState(false), [recording, setRecording] = useState(false), [seconds, setSeconds] = useState(0), [facing, setFacing] = useState<"user" | "environment">("user"), [error, setError] = useState(""), [streamTick, setStreamTick] = useState(0), [settings, setSettings] = useState<MediaTrackSettings | null>(null);
  const cleanup = () => { if (timer.current) clearInterval(timer.current); if (stopAt.current) clearTimeout(stopAt.current); timer.current = null; stopAt.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; if (live.current) live.current.srcObject = null; };
  useEffect(() => () => cleanup(), []);
  useEffect(() => { if (!open) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previous; }; }, [open]);
  useEffect(() => { const player = live.current; if (!player || !stream.current) return; player.srcObject = stream.current; const play = () => { void player.play().catch(() => undefined); }; player.onloadedmetadata = play; player.oncanplay = play; play(); return () => { player.onloadedmetadata = null; player.oncanplay = null; }; }, [open, streamTick]);
  const mime = () => ["video/webm;codecs=vp9,opus", "video/webm;codecs=vp8,opus", "video/webm", "video/mp4"].find(value => GLIMPS_VIDEO_MIME_TYPES.includes(value.split(";")[0] as any) && typeof MediaRecorder !== "undefined" && MediaRecorder.isTypeSupported(value));
  const startCamera = async (next = facing) => { const version = ++request.current; setError(""); setOpen(true); onCaptureStateChange?.(true); if (!navigator.mediaDevices?.getUserMedia) return setError("Camera isn't available on this browser. Upload a video instead."); if (typeof MediaRecorder === "undefined" || !mime()) return setError("Camera recording isn't supported on this browser. Upload a video instead."); cleanup(); const constraints = { video: { facingMode: { ideal: next }, aspectRatio: { ideal: 9 / 16 }, width: { ideal: 720 }, height: { ideal: 1280 }, frameRate: { ideal: 30, max: 30 } }, audio: true }; try { let value: MediaStream; try { value = await navigator.mediaDevices.getUserMedia(constraints); } catch { value = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); } if (version !== request.current) { value.getTracks().forEach(track => track.stop()); return; } stream.current = value; setSettings(value.getVideoTracks()[0]?.getSettings() || null); setFacing(next); setStreamTick(tick => tick + 1); } catch { if (version === request.current) setError("We couldn't access your camera and microphone. Check permissions, then try again."); } };
  const stopRecording = () => { if (recorder.current?.state === "recording") recorder.current.stop(); };
  const record = () => { const type = mime(); if (!stream.current || !type || recording) return; discardRecording.current = false; chunks.current = []; const value = new MediaRecorder(stream.current, { mimeType: type }); recorder.current = value; value.ondataavailable = event => { if (event.data.size) chunks.current.push(event.data); }; value.onerror = () => { setError("Recording failed. Please try again."); cleanup(); setRecording(false); }; value.onstop = () => { if (discardRecording.current) { cleanup(); setRecording(false); setOpen(false); onCaptureStateChange?.(false); return; } const actual = value.mimeType || type, blob = new Blob(chunks.current, { type: actual }), extension = actual.startsWith("video/mp4") ? "mp4" : "webm"; cleanup(); setRecording(false); setOpen(false); onCaptureStateChange?.(false); onVideo(new File([blob], `glimps-recording-${Date.now()}.${extension}`, { type: actual })); }; value.start(); setSeconds(0); setRecording(true); timer.current = setInterval(() => setSeconds(value => value + 1), 1000); stopAt.current = setTimeout(stopRecording, 60000); };
  const closeCamera = () => { ++request.current; discardRecording.current = true; stopRecording(); cleanup(); setRecording(false); setOpen(false); onCaptureStateChange?.(false); };
  if (!open) return <button type="button" onClick={() => void startCamera()} className="flex min-h-40 w-full flex-col items-center justify-center rounded-3xl border border-brand-indigo/25 bg-brand-indigo/[.04] p-4 text-center"><span className="grid h-12 w-12 place-items-center rounded-full bg-brand-indigo text-white"><Camera /></span><b className="mt-3">Camera</b><span className="mt-1 text-caption leading-4 text-brand-slate">Record in portrait</span></button>;
  return <div className="fixed inset-0 z-[60] h-[100dvh] overflow-hidden bg-black text-white"><video ref={live} playsInline muted className="absolute inset-0 h-full w-full bg-black object-contain" /><div className="absolute inset-x-0 top-0 flex items-center justify-between bg-gradient-to-b from-black/65 to-transparent px-4 pb-10 pt-[calc(1rem+env(safe-area-inset-top))]"><p className="text-body-sm font-extrabold tracking-wide">Create GLIMPS</p><button type="button" onClick={closeCamera} className="grid h-11 w-11 place-items-center rounded-full bg-black/45 backdrop-blur" aria-label="Close camera"><X className="h-6 w-6" /></button></div>{error && <div className="absolute inset-x-4 top-[calc(5rem+env(safe-area-inset-top))] rounded-2xl bg-black/75 p-4 text-body-sm text-red-100 backdrop-blur" role="alert"><p>{error}</p><button type="button" onClick={() => void startCamera()} className="mt-3 font-bold text-white underline">Try camera again</button></div>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent px-5 pb-[calc(1.5rem+env(safe-area-inset-bottom))] pt-16"><div className="mx-auto flex max-w-sm items-center justify-between gap-5"><button type="button" onClick={() => void startCamera(facing === "user" ? "environment" : "user")} disabled={recording} className="grid h-12 w-12 place-items-center rounded-full bg-black/45 backdrop-blur disabled:opacity-40" aria-label="Flip Camera"><FlipHorizontal className="h-6 w-6" /></button><div className="flex flex-col items-center gap-3"><span className="rounded-full bg-black/45 px-3 py-1 text-caption font-bold tabular-nums backdrop-blur">{stamp(seconds)} / 01:00</span><button type="button" onClick={recording ? stopRecording : record} disabled={!!error} className="grid h-[4.75rem] w-[4.75rem] place-items-center rounded-full border-4 border-white bg-white/20 p-1 disabled:opacity-40" aria-label={recording ? "Stop recording" : "Start recording"}><span className={`grid h-full w-full place-items-center bg-brand-coral transition-all ${recording ? "rounded-2xl" : "rounded-full"}`}>{recording ? <Square className="h-6 w-6 fill-current" /> : <Video className="h-7 w-7" />}</span></button><span className="text-caption font-bold">{recording ? "Stop" : "Record"}</span></div><span className="h-12 w-12" aria-hidden="true" /></div>{settings && <p className="mt-4 text-center text-[10px] text-white/55">{settings.width || "?"} × {settings.height || "?"} · {settings.facingMode || facing}</p>}</div></div>;
}
