"use client";

import Link from "next/link";
import { Loader2, Mic } from "lucide-react";
import { useState } from "react";
import { PostCard, type Post } from "@/components/social/SocialHomeFeed";

export default function JoxFeed({ initialItems, initialCursor, authHref }: { initialItems: Post[]; initialCursor: string | null; authHref?: string }) {
  const [items, setItems] = useState(initialItems), [cursor, setCursor] = useState(initialCursor), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const more = async () => { if (!cursor || busy) return; setBusy(true); setError(""); try { const response = await fetch(`/api/social/vijox?cursor=${encodeURIComponent(cursor)}`), data = await response.json(); if (!response.ok) throw Error(); setItems(current => [...current, ...(data.items || []).filter((item: Post) => !current.some(existing => existing.id === item.id))]); setCursor(data.nextCursor || null); } catch { setError("Could not load more Jox."); } finally { setBusy(false); } };
  return <section className="mx-auto max-w-3xl"><header className="rounded-3xl border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-brand-indigo/[.06] p-5 shadow-soft sm:p-7"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-brand-indigo text-white"><Mic className="h-5 w-5" /></span><div><p className="text-caption font-bold tracking-[.15em] text-violet-700">VIJOX</p><h1 className="mt-1 text-h2 font-extrabold text-brand-midnight">Jox your voice.</h1><p className="mt-1 text-body-sm text-brand-slate">Short voice notes from professionals you want to hear.</p></div></div><Link href={authHref || "/social/vijox/create"} className="mt-5 inline-flex min-h-10 items-center rounded-xl bg-brand-indigo px-4 py-2 text-caption font-bold text-white">Create a Jox</Link></header><div className="mt-6 space-y-4">{items.map(post => <PostCard key={post.id} post={post} authHref={authHref} onRefresh={() => location.reload()} />)}{!items.length && <div className="rounded-2xl border border-brand-borderLight bg-white p-8 text-center text-body-sm text-brand-slate">No Jox yet. Start the conversation with your voice.</div>}{error && <button type="button" onClick={() => void more()} className="font-bold text-brand-indigo">Retry</button>}{busy && <Loader2 className="mx-auto h-5 w-5 animate-spin text-brand-indigo" />}{cursor && !busy && <button type="button" onClick={() => void more()} className="w-full rounded-xl border border-brand-indigo/20 bg-white py-3 text-caption font-bold text-brand-indigo">Load more Jox</button>}</div></section>;
}
