"use client";
import Link from "next/link";
import { Play } from "lucide-react";
import type { Post } from "@/components/social/SocialHomeFeed";

export default function JoxOrbitRail({ items }: { items: Post[] }) {
  if (!items.length) return null;
  return <section className="mt-7 min-w-0 border-b border-brand-borderLight/70 pb-5"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-extrabold tracking-[.16em] text-violet-700">JOX</p><h2 className="mt-0.5 font-extrabold text-brand-midnight">Voices on GigWay</h2></div><Link href="/social/vijox" className="text-caption font-bold text-brand-indigo">See all →</Link></div><div className="-mx-4 flex snap-x gap-4 overflow-x-auto px-4 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mx-0 sm:px-0">{items.map((post,index) => { const cover=post.joxCover?.url||post.author?.avatar; const duration=post.media.find(media=>media.type==="audio")?.durationSeconds; return <Link key={post.id} href={`/social/posts/${post.id}`} aria-label={`Open Jox by ${post.author?.name||"GigWay member"}`} className={`w-[76px] shrink-0 snap-start text-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-indigo ${index%2?"translate-y-2":""}`}><span className="relative mx-auto grid h-[72px] w-[72px] place-items-center overflow-hidden rounded-full border-2 border-violet-300 bg-gradient-to-br from-violet-100 via-white to-cyan-100 p-1 shadow-[0_5px_16px_-10px_rgba(79,70,229,.55)]">{cover?<img src={cover} alt="" className="h-full w-full rounded-full object-cover"/>:<img src="/logo.png" alt="GigWay VIJOX" className="w-[62%] object-contain"/>}<span className="absolute bottom-0 right-0 grid h-5 w-5 place-items-center rounded-full bg-brand-indigo text-white"><Play className="ml-px h-2.5 w-2.5 fill-current"/></span></span><span className="mt-2 block truncate text-[11px] font-bold text-brand-midnight">{post.author?.name?.split(" ")[0]||"GigWay"}</span>{duration?<span className="block text-[10px] text-brand-slate">{Math.round(duration)}s</span>:null}</Link>})}</div></section>;
}
