"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, ChevronDown, ChevronUp, Loader2, MessageSquare, Pencil, Trash2, X } from "lucide-react";
import { ProfileAvatar } from "@/components/ui/profile-avatar";
import { PostCard, type Post } from "@/components/social/SocialHomeFeed";
import GlimpsExperience from "@/components/social/GlimpsExperience";

type Comment = { id: string; parentCommentId: string | null; body: string; createdAt: string; author: { id: string; name: string; username?: string | null; avatar?: string | null; verified?: boolean } | null };
type Target = { root: string; username?: string | null; name: string } | null;

function relativeTime(value: string) { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); if (minutes < 1) return "now"; if (minutes < 60) return `${minutes}m`; if (minutes < 1440) return `${Math.floor(minutes / 60)}h`; if (minutes < 10080) return `${Math.floor(minutes / 1440)}d`; return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric" }); }

function Composer({ postId, target, onDone, onCancel }: { postId: string; target?: Target; onDone: () => void; onCancel?: () => void }) {
  const ref = useRef<HTMLTextAreaElement>(null), [body, setBody] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { if (target) requestAnimationFrame(() => ref.current?.focus()); }, [target]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!body.trim() || busy) return; setBusy(true); setError(""); try { const response = await fetch(`/api/social/posts/${postId}/comments`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ body, targetCommentId: target?.root }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not post comment."); setBody(""); onDone(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not post comment."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className={target ? "mt-3 rounded-xl bg-brand-ivory p-3" : "mt-4 border-t border-brand-borderLight pt-4"}>{target && <div className="mb-2 flex items-center justify-between text-caption text-brand-slate">Replying to <b className="text-brand-indigo">{target.username ? `@${target.username}` : target.name}</b><button type="button" onClick={onCancel} aria-label="Cancel reply"><X className="h-4 w-4" /></button></div>}<textarea ref={ref} value={body} onChange={event => setBody(event.target.value.slice(0, 2000))} rows={target ? 2 : 3} maxLength={2000} placeholder={target ? "Write a reply…" : "Add a comment…"} className="w-full resize-none rounded-xl border border-brand-borderLight bg-white p-3 text-body-sm outline-none focus:border-brand-indigo" />{error && <p className="mt-1 text-caption text-brand-coral">{error}</p>}<div className="mt-2 flex justify-end"><button disabled={busy || !body.trim()} className="rounded-lg bg-brand-indigo px-3 py-2 text-caption font-bold text-white disabled:opacity-60">{busy ? "Posting…" : target ? "Reply" : "Comment"}</button></div></form>;
}

type ItemProps = { postId: string; comment: Comment; replies: Comment[]; viewerId?: string; target: Target; onReply: (comment: Comment) => void; onCancelReply: () => void; onChanged: () => void };
function CommentItem({ postId, comment, replies, viewerId, target, onReply, onCancelReply, onChanged }: ItemProps) {
  const [open, setOpen] = useState(false), [editing, setEditing] = useState(false), [text, setText] = useState(comment.body), [busy, setBusy] = useState(false);
  const own = comment.author?.id === viewerId, href = comment.author?.username ? `/u/${comment.author.username}` : null, replyingHere = target?.root === comment.id;
  async function save() { if (!text.trim() || busy) return; setBusy(true); try { const response = await fetch(`/api/social/comments/${comment.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ body: text }) }); if (!response.ok) throw new Error(); setEditing(false); onChanged(); } finally { setBusy(false); } }
  async function remove() { if (busy) return; setBusy(true); try { await fetch(`/api/social/comments/${comment.id}`, { method: "DELETE" }); onChanged(); } finally { setBusy(false); } }
  function startReply(reply: Comment) { if (!viewerId) { location.assign(`/login?next=${encodeURIComponent(location.pathname)}`); return; } if (replies.length) setOpen(true); onReply(reply); }
  return <article className="py-4 first:pt-3"><div className="flex gap-3"><ProfileAvatar src={comment.author?.avatar} name={comment.author?.name} className="h-9 w-9 shrink-0 text-xs" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-1.5 text-caption">{href ? <Link href={href} className="font-bold text-brand-midnight">{comment.author?.name}</Link> : <b>{comment.author?.name || "GigWay member"}</b>}{comment.author?.verified && <CheckCircle2 className="h-3.5 w-3.5 text-brand-indigo" />}<span className="text-brand-slate">· {relativeTime(comment.createdAt)}</span></div>{editing ? <><textarea value={text} onChange={event => setText(event.target.value.slice(0, 2000))} rows={2} className="mt-2 w-full resize-none rounded-lg border border-brand-borderLight p-2 text-body-sm" /><div className="mt-2 flex gap-2"><button onClick={save} disabled={busy || !text.trim()} className="text-caption font-bold text-brand-indigo disabled:opacity-50">Save</button><button onClick={() => { setText(comment.body); setEditing(false); }} className="text-caption font-bold text-brand-slate">Cancel</button></div></> : <p className="mt-1 whitespace-pre-wrap break-words text-body-sm leading-6 text-brand-midnight">{comment.body}</p>}{!editing && <div className="mt-2 flex items-center gap-4 text-caption font-bold text-brand-slate"><button onClick={() => startReply(comment)}><MessageSquare className="mr-1 inline h-3.5 w-3.5" />Reply</button>{own && <><button aria-label="Edit comment" onClick={() => setEditing(true)}><Pencil className="h-3.5 w-3.5" /></button><button aria-label="Delete comment" disabled={busy} onClick={remove} className="text-brand-coral"><Trash2 className="h-3.5 w-3.5" /></button></>}</div>}{replyingHere && viewerId && <Composer postId={postId} target={target} onDone={onChanged} onCancel={onCancelReply} />}</div></div>{replies.length > 0 && <div className="ml-12 mt-2"><button onClick={() => setOpen(value => !value)} aria-expanded={open} className="flex items-center gap-1 text-caption font-bold text-brand-indigo">{open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}{open ? "Hide replies" : `${replies.length} ${replies.length === 1 ? "reply" : "replies"}`}</button>{open && <div className="mt-1">{replies.map(reply => <div key={reply.id} className="border-t border-brand-borderLight/70"><CommentItem postId={postId} comment={reply} replies={[]} viewerId={viewerId} target={target} onReply={onReply} onCancelReply={onCancelReply} onChanged={onChanged} /></div>)}</div>}</div>}</article>;
}

export default function PostDetailContent({ post, viewerId }: { post: Post; viewerId?: string }) {
  const router = useRouter(), [comments, setComments] = useState<Comment[]>([]), [loading, setLoading] = useState(true), [target, setTarget] = useState<Target>(null);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/social/posts/${post.id}/comments`), data = await response.json(); if (response.ok) setComments(data.items || []); } finally { setLoading(false); } }, [post.id]);
  useEffect(() => { load(); }, [load]);
  const done = () => { setTarget(null); load(); router.refresh(); }, top = comments.filter(comment => !comment.parentCommentId);
  const closeComments = () => window.history.length > 1 ? router.back() : router.push("/social");
  return <main className="min-h-screen bg-brand-ivory px-4 py-8 pb-24"><div className="mx-auto max-w-2xl">{post.contentFormat === "glimps" ? <GlimpsExperience post={post} authHref={viewerId ? undefined : `/login?next=/social/posts/${post.id}`} onRefresh={done} onComments={() => document.getElementById("post-comments")?.scrollIntoView({ behavior: "smooth", block: "start" })} /> : <PostCard post={post} authHref={viewerId ? undefined : `/login?next=/social/posts/${post.id}`} onRefresh={done} />}<section id="post-comments" className="mt-5 rounded-2xl border border-brand-borderLight bg-white p-4 shadow-soft sm:p-5"><div className="flex items-center justify-between"><h1 className="text-h3 font-extrabold text-brand-midnight">Comments</h1><button type="button" onClick={closeComments} aria-label="Close comments and go back" className="grid h-10 w-10 place-items-center rounded-full text-brand-midnight transition hover:bg-brand-ivory"><X className="h-6 w-6" /></button></div>{viewerId ? <Composer postId={post.id} onDone={done} /> : <p className="mt-3 text-body-sm text-brand-slate">Sign in to join the conversation.</p>}<div className="mt-4 border-t border-brand-borderLight">{loading ? <Loader2 className="mx-auto my-8 animate-spin text-brand-indigo" /> : top.map(comment => <CommentItem key={comment.id} postId={post.id} comment={comment} replies={comments.filter(reply => reply.parentCommentId === comment.id)} viewerId={viewerId} target={target} onReply={reply => setTarget({ root: reply.parentCommentId || reply.id, username: reply.author?.username, name: reply.author?.name || "this member" })} onCancelReply={() => setTarget(null)} onChanged={done} />)}</div></section></div></main>;
}
