"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { BriefcaseBusiness, Loader2, Package, Repeat2, Building2 } from "lucide-react"
import { PostCard, type FeedItem, type MarketplaceShare, type Post } from "@/components/social/SocialHomeFeed"
import GlimpsExperience from "@/components/social/GlimpsExperience"

export default function ProfileSocialFeed({ profileId, name }: { profileId: string; name: string }) {
  type Tab = "gigthoughts" | "jox" | "glimps" | "reposts"
  type Page = { items: FeedItem[]; nextCursor: string | null; loaded: boolean }
  const tabs: { value: Tab; label: string; empty: string }[] = [{ value: "gigthoughts", label: "GigThoughts", empty: "No GigThoughts yet." }, { value: "jox", label: "JOX", empty: "No JOX yet." }, { value: "glimps", label: "GLIMPS", empty: "No GLIMPS yet." }, { value: "reposts", label: "Reposts", empty: "No reposts yet." }]
  const blank = (): Page => ({ items: [], nextCursor: null, loaded: false })
  const [tab, setTab] = useState<Tab>("gigthoughts"), [pages, setPages] = useState<Record<Tab, Page>>({ gigthoughts: blank(), jox: blank(), glimps: blank(), reposts: blank() }), [loading, setLoading] = useState(false)
  const load = async (reset = false) => { const page = pages[tab]; if (!reset && page.loaded && !page.nextCursor) return; setLoading(true); try { const cursor = !reset ? page.nextCursor : null, response = await fetch(`/api/social/profiles/${profileId}/posts?tab=${tab}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`), data = await response.json(); if (!response.ok || !Array.isArray(data.items)) throw Error(); setPages(current => ({ ...current, [tab]: { items: reset ? data.items : [...current[tab].items, ...data.items], nextCursor: data.nextCursor || null, loaded: true } })) } catch { setPages(current => ({ ...current, [tab]: { ...blank(), loaded: true } })) } finally { setLoading(false) } }
  useEffect(() => { setPages({ gigthoughts: blank(), jox: blank(), glimps: blank(), reposts: blank() }) }, [profileId])
  useEffect(() => { if (!pages[tab].loaded && !loading) void load() }, [tab, pages, loading]) // eslint-disable-line react-hooks/exhaustive-deps
  const items = pages[tab].items, active = tabs.find(item => item.value === tab)!
  const renderPost = (post: Post) => tab === "glimps" ? <GlimpsExperience post={post} onRefresh={() => void load(true)} /> : <PostCard post={post} onRefresh={() => void load(true)} />
  return <section className="mt-6"><div className="-mx-1 flex gap-1 overflow-x-auto rounded-xl bg-white/[.06] p-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{tabs.map(item => <button key={item.value} type="button" onClick={() => setTab(item.value)} className={`min-w-max flex-1 rounded-lg px-3 py-2 text-sm font-bold transition-colors ${tab === item.value ? "bg-[#6D5DFB] text-white" : "text-[#CBD5E1] hover:bg-white/[.05]"}`}>{item.label}</button>)}</div><div className="mt-4 space-y-4">{items.map(item => { if ("type" in item && item.type === "marketplace_share") { const share = item as MarketplaceShare; const label = `${share.verb === "shared" ? "Shared" : "Reposted"} a ${share.object.type === "service" ? "Service" : share.object.type[0].toUpperCase() + share.object.type.slice(1)}`, Icon = share.object.type === "job" ? BriefcaseBusiness : share.object.type === "project" ? Building2 : Package; return <div key={share.shareId}><p className="mb-2 flex items-center gap-1.5 text-xs text-[#9EA6B8]"><Repeat2 className="h-3.5 w-3.5" />{name} {label.toLowerCase()}</p><Link href={share.object.href} className="block max-w-full rounded-2xl bg-white/[.035] p-4 ring-1 ring-white/8 hover:bg-white/[.06]"><div className="flex min-w-0 gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#6D5DFB]/15 text-[#B9B3FF]"><Icon className="h-5 w-5" /></span><div className="min-w-0"><p className="truncate font-bold text-white">{share.object.title}</p><p className="mt-1 line-clamp-2 text-xs text-[#B8C0D0]">{share.object.subtitle}</p></div></div><p className="mt-3 text-xs font-bold text-[#B9B3FF]">{share.object.cta}</p></Link></div> } const repost = "type" in item ? item : null, post = (repost ? repost.originalPost : item) as Post; return <div key={repost ? `r-${repost.repostedAt}-${post.id}` : post.id}>{repost && <p className="mb-2 flex items-center gap-1 text-xs text-[#9EA6B8]"><Repeat2 className="h-3.5 w-3.5" />{name} reposted</p>}{renderPost(post)}</div> })}{loading && <Loader2 className="mx-auto animate-spin text-[#A99FFF]" />}{!loading && !items.length && <p className="rounded-xl bg-white/[.035] p-4 text-sm text-[#B8C0D0]">{active.empty}</p>}{!loading && pages[tab].nextCursor && <button type="button" onClick={() => void load()} className="w-full rounded-xl bg-white/[.06] py-3 text-sm font-bold text-[#B9B3FF] hover:bg-white/[.1]">Load more</button>}</div></section>
}
