"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { BriefcaseBusiness, Loader2, Package, Repeat2, Building2 } from "lucide-react"
import { PostCard, type FeedItem, type MarketplaceShare, type Post } from "@/components/social/SocialHomeFeed"

export default function ProfileSocialFeed({ profileId, name }: { profileId: string; name: string }) {
  const [tab, setTab] = useState<"posts" | "reposts">("posts"), [items, setItems] = useState<FeedItem[]>([]), [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const response = await fetch(`/api/social/profiles/${profileId}/posts?tab=${tab}`), data = await response.json(); if (!response.ok || !Array.isArray(data.items)) throw Error(); setItems(data.items) } catch { setItems([]) } finally { setLoading(false) } }
  useEffect(() => { load() }, [tab, profileId])
  return <section className="mt-6"><div className="flex rounded-xl bg-white/[.06] p-1"><button onClick={() => setTab("posts")} className={`flex-1 rounded-lg py-2 text-sm font-bold ${tab === "posts" ? "bg-[#6D5DFB] text-white" : "text-[#CBD5E1]"}`}>Posts</button><button onClick={() => setTab("reposts")} className={`flex-1 rounded-lg py-2 text-sm font-bold ${tab === "reposts" ? "bg-[#6D5DFB] text-white" : "text-[#CBD5E1]"}`}>Reposts</button></div><div className="mt-4 space-y-4">{items.map(item => { if ("type" in item && item.type === "marketplace_share") { const share = item as MarketplaceShare; const label = `${share.verb === "shared" ? "Shared" : "Reposted"} a ${share.object.type === "service" ? "Service" : share.object.type[0].toUpperCase() + share.object.type.slice(1)}`, Icon = share.object.type === "job" ? BriefcaseBusiness : share.object.type === "project" ? Building2 : Package; return <div key={share.shareId}><p className="mb-2 flex items-center gap-1.5 text-xs text-[#9EA6B8]"><Repeat2 className="h-3.5 w-3.5" />{name} {label.toLowerCase()}</p><Link href={share.object.href} className="block max-w-full rounded-2xl bg-white/[.035] p-4 ring-1 ring-white/8 hover:bg-white/[.06]"><div className="flex min-w-0 gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#6D5DFB]/15 text-[#B9B3FF]"><Icon className="h-5 w-5" /></span><div className="min-w-0"><p className="truncate font-bold text-white">{share.object.title}</p><p className="mt-1 line-clamp-2 text-xs text-[#B8C0D0]">{share.object.subtitle}</p></div></div><p className="mt-3 text-xs font-bold text-[#B9B3FF]">{share.object.cta}</p></Link></div> } const repost = "type" in item ? item : null, post = (repost ? repost.originalPost : item) as Post; return <div key={repost ? `r-${repost.repostedAt}-${post.id}` : post.id}>{repost && <p className="mb-2 flex items-center gap-1 text-xs text-[#9EA6B8]"><Repeat2 className="h-3.5 w-3.5" />{name} reposted</p>}<PostCard post={post} onRefresh={load} /></div> })}{loading && <Loader2 className="mx-auto animate-spin text-[#A99FFF]" />}{!loading && !items.length && <p className="rounded-xl bg-white/[.035] p-4 text-sm text-[#B8C0D0]">{tab === "posts" ? "No posts yet." : "No reposts yet."}</p>}</div></section>
}
