"use client";
import { Pause, Play } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { announceMediaPlay, MEDIA_PLAY_EVENT } from "@/lib/social/media-playback";
const clock=(n:number)=>`00:${Math.max(0,Math.floor(n)).toString().padStart(2,"0")}`;
export default function VijoxPlayer({src,duration,avatar,name="GigWay member"}:{src:string;duration?:number|null;avatar?:string|null;name?:string}){
 const audio=useRef<HTMLAudioElement>(null),id=useRef(`vijox-${crypto.randomUUID()}`),[playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[total,setTotal]=useState(duration||27);
 const progress=Math.min(100,current/total*100),ring={background:`conic-gradient(from -90deg,#ec4899 0deg,#8b5cf6 ${Math.max(18,progress*3.6)}deg,#4f46e5 ${Math.max(18,progress*3.6+35)}deg,#06b6d4 ${Math.max(18,progress*3.6+70)}deg,#e8eaf0 ${Math.max(18,progress*3.6+70)}deg 360deg)`};
 useEffect(()=>{const pause=(e:Event)=>{if((e as CustomEvent<string>).detail!==id.current)audio.current?.pause()};window.addEventListener(MEDIA_PLAY_EVENT,pause);return()=>window.removeEventListener(MEDIA_PLAY_EVENT,pause)},[]);
 const toggle=async()=>{const player=audio.current;if(!player)return;if(player.paused){if(player.ended)player.currentTime=0;announceMediaPlay(id.current);try{await player.play();setPlaying(true)}catch{setPlaying(false)}}else{player.pause();setPlaying(false)}};
 return <div className="mt-4 rounded-2xl border border-violet-200 bg-gradient-to-br from-pink-50 via-white to-cyan-50 p-4"><audio ref={audio} src={src} preload="metadata" onLoadedMetadata={()=>{if(audio.current&&Number.isFinite(audio.current.duration))setTotal(audio.current.duration)}} onTimeUpdate={()=>setCurrent(audio.current?.currentTime||0)} onEnded={()=>{setPlaying(false);setCurrent(total)}} onError={()=>setPlaying(false)}/><div className="flex items-center gap-3"><div className={`grid h-16 w-16 shrink-0 place-items-center rounded-full p-1.5 shadow-[0_6px_20px_rgba(124,58,237,.14)] ${playing?"motion-safe:animate-pulse":""}`} style={ring}><span className="grid h-full w-full place-items-center overflow-hidden rounded-full bg-white font-extrabold text-brand-indigo">{avatar?<img src={avatar} alt="" className="h-full w-full object-cover"/>:name.trim().charAt(0).toUpperCase()}</span></div><div className="min-w-0 flex-1"><p className="text-[10px] font-extrabold tracking-[.14em] text-violet-700">VIJOX</p><p className="mt-0.5 text-caption text-brand-slate">Share your voice</p><p className="mt-1 text-caption font-bold tabular-nums text-brand-midnight">{clock(current)} <span className="text-brand-slate">/ {clock(total)}</span></p></div><button onClick={toggle} aria-label={playing?"Pause VIJOX":"Play VIJOX"} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-brand-indigo text-white shadow-sm hover:bg-brand-indigoDark">{playing?<Pause className="h-4 w-4"/>:<Play className="ml-0.5 h-4 w-4"/>}</button></div></div>
}
