"use client";

import { useEffect, useRef, useState } from "react";
import { Volume2, VolumeX } from "lucide-react";
import { announceMediaPlay, MEDIA_PLAY_EVENT } from "@/lib/social/media-playback";
import VijoxTranscript, { type VijoxTranscriptData } from "@/components/social/VijoxTranscript";
import VijoxTimedReactions from "@/components/social/VijoxTimedReactions";
import VijoxReactionMoments from "@/components/social/VijoxReactionMoments";
import VijoxCircularProgress from "@/components/social/VijoxCircularProgress";
import type { VijoxTimedReactionSummary } from "@/lib/social/vijox-timed-reactions";

const clock = (seconds: number) => `00:${Math.max(0, Math.floor(seconds)).toString().padStart(2, "0")}`;
export type VijoxExperienceProps = { src: string; duration?: number | null; avatar?: string | null; name?: string; transcript?: VijoxTranscriptData | null; imageUrl?: string | null; imageAlt?: string; postId?: string | null; compact?: boolean; initialTimedReactionSummary?: VijoxTimedReactionSummary };

export default function VijoxExperience({ src, duration, avatar, name = "GigWay member", transcript, imageUrl, imageAlt = "VIJOX scene image", postId, compact = false, initialTimedReactionSummary }: VijoxExperienceProps) {
  const audio = useRef<HTMLAudioElement>(null), id = useRef(`vijox-${crypto.randomUUID()}`), context = useRef<AudioContext | null>(null), source = useRef<MediaElementAudioSourceNode | null>(null), analyser = useRef<AnalyserNode | null>(null), gain = useRef<GainNode | null>(null), nodes = useRef<AudioNode[]>([]), frame = useRef<number | null>(null), assist = useRef(1);
  const [playing, setPlaying] = useState(false), [current, setCurrent] = useState(0), [total, setTotal] = useState(duration || 27), [energy, setEnergy] = useState(0), [volume, setVolume] = useState(1.1), [muted, setMuted] = useState(false), [audioError, setAudioError] = useState(""), [reactionSummary, setReactionSummary] = useState<VijoxTimedReactionSummary | null>(initialTimedReactionSummary || null);
  const stopVisualizing = () => { if (frame.current) cancelAnimationFrame(frame.current); frame.current = null; setEnergy(0); };
  const teardown = () => { stopVisualizing(); nodes.current.forEach(node => node.disconnect()); nodes.current = []; context.current?.close().catch(() => undefined); analyser.current = null; gain.current = null; source.current = null; context.current = null; };
  const startVisualizing = () => {
    const player = audio.current; if (!player || analyser.current) return;
    try { const nextContext = new AudioContext(), nextSource = nextContext.createMediaElementSource(player), highpass = nextContext.createBiquadFilter(), presence = nextContext.createBiquadFilter(), compressor = nextContext.createDynamicsCompressor(), nextGain = nextContext.createGain(), limiter = nextContext.createDynamicsCompressor(), nextAnalyser = nextContext.createAnalyser(); highpass.type = "highpass"; highpass.frequency.value = 75; presence.type = "peaking"; presence.frequency.value = 2600; presence.Q.value = .8; presence.gain.value = 1.8; compressor.threshold.value = -22; compressor.knee.value = 18; compressor.ratio.value = 2; compressor.attack.value = .01; compressor.release.value = .18; limiter.threshold.value = -3; limiter.knee.value = 4; limiter.ratio.value = 8; limiter.attack.value = .003; limiter.release.value = .12; nextGain.gain.value = Math.max(0, Math.min(1.4, muted ? 0 : volume)); nextAnalyser.fftSize = 256; nextSource.connect(highpass); highpass.connect(presence); presence.connect(compressor); compressor.connect(nextGain); nextGain.connect(limiter); limiter.connect(nextAnalyser); nextAnalyser.connect(nextContext.destination); context.current = nextContext; source.current = nextSource; analyser.current = nextAnalyser; gain.current = nextGain; nodes.current = [nextSource, highpass, presence, compressor, nextGain, limiter, nextAnalyser]; const values = new Uint8Array(nextAnalyser.fftSize); const tick = () => { nextAnalyser.getByteTimeDomainData(values); let sum = 0; values.forEach(value => { const normalized = (value - 128) / 128; sum += normalized * normalized; }); const rms=Math.sqrt(sum / values.length), target=rms<.035?1.12:rms>.13?.96:1; assist.current += (target-assist.current)*.015; nextGain.gain.setTargetAtTime(Math.max(0,Math.min(1.4,(muted?0:volume)*assist.current)),nextContext.currentTime,.08); setEnergy(Math.min(1, rms * 5)); frame.current = requestAnimationFrame(tick); }; nextContext.resume().then(tick).catch(stopVisualizing); } catch { setEnergy(0); }
  };
  useEffect(() => { const pauseOther = (event: Event) => { if ((event as CustomEvent<string>).detail !== id.current) audio.current?.pause(); }; window.addEventListener(MEDIA_PLAY_EVENT, pauseOther); return () => { window.removeEventListener(MEDIA_PLAY_EVENT, pauseOther); teardown(); }; }, []);
  useEffect(() => { try { const stored=localStorage.getItem("gigway:jox-volume"); if(stored!==null){const value=Number(stored);if(Number.isFinite(value))setVolume(Math.max(0,Math.min(1.4,value)));} } catch {} }, []);
  useEffect(() => { try { localStorage.setItem("gigway:jox-volume",String(volume)); } catch {} if (gain.current && context.current) gain.current.gain.setTargetAtTime(Math.max(0, Math.min(1.4, muted?0:volume)), context.current.currentTime, .03); else if (audio.current) audio.current.volume = muted?0:Math.min(1, volume); }, [volume,muted]);
  const toggle = async () => { const player = audio.current; if (!player) return; if (player.paused) { if (player.ended) player.currentTime = 0; setAudioError(""); announceMediaPlay(id.current); try { await player.play(); setPlaying(true); startVisualizing(); } catch { setPlaying(false); teardown(); setAudioError("This Jox could not play. Please try again."); } } else player.pause(); };
  return <div className={`rounded-2xl border border-violet-200 bg-gradient-to-br from-pink-50 via-white to-cyan-50 ${compact ? "p-3" : "p-4"}`}>
    <audio ref={audio} src={src} preload="metadata" onCanPlay={() => setAudioError("")} onLoadedMetadata={() => { if (audio.current && Number.isFinite(audio.current.duration)) setTotal(audio.current.duration); }} onTimeUpdate={() => setCurrent(audio.current?.currentTime || 0)} onPause={() => { setPlaying(false); teardown(); }} onEnded={() => { setPlaying(false); setCurrent(total); teardown(); }} onError={() => { setPlaying(false); teardown(); setAudioError("This Jox could not load. Please try again."); }} />
    {imageUrl && <div className={`relative -mx-3 -mt-3 mb-3 overflow-hidden rounded-t-xl bg-brand-ivory shadow-[0_12px_30px_rgba(124,58,237,.10)] sm:-mx-4 sm:-mt-4 ${playing ? "ring-2 ring-violet-300/60" : ""}`}><img src={imageUrl} alt={imageAlt} className="h-44 w-full object-cover transition-transform duration-500 motion-reduce:transition-none sm:h-56 hover:scale-[1.015]" /><div aria-hidden className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-white/95 via-white/30 to-transparent" /></div>}
    <div className="text-center"><p className="text-[10px] font-extrabold tracking-[.14em] text-violet-700">VIJOX</p><p className="mt-0.5 text-caption text-brand-slate">Share your voice.</p><div className="mt-3"><VijoxCircularProgress currentTimeMs={Math.round(current * 1000)} durationMs={Math.round(total * 1000)} energy={energy} summary={reactionSummary} playing={playing} onToggle={toggle} label={`${clock(current)} of ${clock(total)} VIJOX playback`} center={<span className="grid h-full w-full place-items-center overflow-hidden rounded-full bg-white font-extrabold text-brand-indigo">{avatar ? <img src={avatar} alt={name} className="h-full w-full object-cover" /> : name.trim().charAt(0).toUpperCase()}</span>} /></div><p className="mt-3 text-caption font-bold tabular-nums text-brand-midnight">{clock(current)} <span className="text-brand-slate">/ {clock(total)}</span></p><label className="mx-auto mt-2 flex w-full max-w-[190px] items-center gap-2 text-caption text-brand-slate"><button type="button" onClick={()=>setMuted(value=>!value)} aria-label={muted?"Unmute Jox":"Mute Jox"} className="text-violet-700">{muted?<VolumeX className="h-3.5 w-3.5"/>:<Volume2 className="h-3.5 w-3.5"/>}</button><input aria-label="Jox volume" type="range" min="0" max="1.4" step="0.05" value={volume} onChange={event => {setMuted(false);setVolume(Number(event.target.value));}} className="min-w-0 flex-1 accent-violet-600" /></label><p className="mt-1 text-[10px] text-violet-700">Voice Enhance</p></div>
    {postId && <VijoxTimedReactions postId={postId} currentTimeMs={() => Math.round((audio.current?.currentTime || 0) * 1000)} summary={reactionSummary} onSummaryChange={setReactionSummary} />}
    {postId && <VijoxReactionMoments summary={reactionSummary} currentTimeMs={Math.round(current * 1000)} durationMs={Math.round(total * 1000)} />}
    {audioError && <p className="mt-2 text-center text-caption text-brand-coral" role="status">{audioError}</p>}
    <VijoxTranscript transcript={transcript} currentSeconds={current} />
  </div>;
}
