"use client";

import Link from "next/link";
import { Loader2, Mic } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { PostCard, type Post } from "@/components/social/SocialHomeFeed";
import { announceMediaPlay } from "@/lib/social/media-playback";

export default function VijoxContinuousFeed({ initialItems, initialCursor, authHref }: { initialItems: Post[]; initialCursor: string | null; authHref?: string }) {
  const [items, setItems] = useState(initialItems), [cursor, setCursor] = useState(initialCursor), [busy, setBusy] = useState(false), [continuous, setContinuous] = useState(false), [active, setActive] = useState(initialItems[0]?.id || ""), [error, setError] = useState("");
  const nodes = useRef(new Map<string, HTMLDivElement>()), loading = useRef(false);
  const more = async () => { if (!cursor || loading.current) return; loading.current = true; setBusy(true); try { const response = await fetch(`/api/social/vijox?cursor=${encodeURIComponent(cursor)}`), data = await response.json(); if (!response.ok) throw Error(); setItems(rows => [...rows, ...(data.items || []).filter((item: Post) => !rows.some(row => row.id === item.id))]); setCursor(data.nextCursor || null); } catch { setError("Could not load more Jox."); } finally { loading.current = false; setBusy(false); } };
  useEffect(() => { const observer = new IntersectionObserver(entries => { const winner = entries.filter(entry => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (!winner) return; const id = winner.target.getAttribute("data-jox") || ""; setActive(id); const index = items.findIndex(item => item.id === id); if (index >= items.length - 3) void more(); }, { threshold: [.55, .72] }); nodes.current.forEach(node => observer.observe(node)); return () => observer.disconnect(); }, [items, cursor]);
  useEffect(() => { nodes.current.forEach((node, id) => { if (id !== active) node.querySelector("audio")?.pause(); }); if (!continuous || !active || document.hidden) return; const player = nodes.current.get(active)?.querySelector("audio"); if (!player || !player.paused) return; announceMediaPlay(`jox-${active}`); player.play().catch(() => undefined); }, [active, continuous]);
  useEffect(() => { const hidden = () => { if (document.hidden) nodes.current.get(active)?.querySelector("audio")?.pause(); }; document.addEventListener("visibilitychange", hidden); return () => document.removeEventListener("visibilitychange", hidden); }, [active]);
  return <section className="mx-auto max-w-3xl"><header className="rounded-3xl border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-brand-indigo/[.06] p-5 shadow-soft sm:p-7"><div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-brand-indigo text-white"><Mic className="h-5 w-5" /></span><div><p className="text-caption font-bold tracking-[.15em] text-violet-700">VIJOX</p><h1 className="mt-1 text-h2 font-extrabold text-brand-midnight">Jox your voice.</h1><p className="mt-1 text-body-sm text-brand-slate">A voice-first stream of short professional Joxes.</p></div></div><div className="mt-5 flex flex-wrap gap-3"><Link href={authHref || "/social/vijox/create"} className="inline-flex min-h-10 items-center rounded-xl bg-brand-indigo px-4 py-2 text-caption font-bold text-white">Create a Jox</Link><button type="button" onClick={() => setContinuous(value => !value)} aria-pressed={continuous} className="min-h-10 rounded-xl border border-violet-200 bg-white px-4 text-caption font-bold text-violet-700">{continuous ? "Continuous Play on" : "Enable Continuous Play"}</button></div></header><div className="mt-6 space-y-5 md:snap-y md:snap-proximity">{items.map(post => <div key={post.id} data-jox={post.id} ref={node => { if (node) nodes.current.set(post.id, node); else nodes.current.delete(post.id); }} className={`scroll-mt-5 md:min-h-[65vh] md:snap-start ${active === post.id ? "rounded-3xl bg-violet-50/40 p-1" : ""}`}><PostCard post={post} authHref={authHref} onRefresh={() => location.reload()} /></div>)}{!items.length && <p className="rounded-2xl bg-white p-6 text-center text-body-sm text-brand-slate">No Jox yet.</p>}{busy && <Loader2 className="mx-auto h-5 w-5 animate-spin text-brand-indigo" />}{error && <button onClick={() => void more()} className="font-bold text-brand-indigo">Retry</button>}{cursor && !busy && <button onClick={() => void more()} className="w-full rounded-xl border border-brand-indigo/20 bg-white py-3 text-caption font-bold text-brand-indigo">Load more Jox</button>}</div></section>;
}
