import Link from "next/link"
import { ArrowRight, BriefcaseBusiness, ClipboardCheck, FileSearch, FolderKanban, Lightbulb, LockKeyhole, ScanSearch, Sparkles, UserRoundCheck } from "lucide-react"
const tools=[
["Resume Intelligence","Understand the strengths, weaknesses and opportunities in your resume.","Resume & Career",FileSearch,true],
["Opportunity Match","See how your resume and profile match a role — and what may be holding you back.","Resume & Career",ScanSearch],
["Job Description Intelligence","Turn a job description into clear skills, requirements and preparation insights.","Resume & Career",ClipboardCheck],
["Career Gap Map","Compare where you are today with the role you want next.","Resume & Career",Lightbulb],
["Profile Intelligence","Make your GigWay professional identity stronger and easier to discover.","Profile & Growth",UserRoundCheck,true],
["Portfolio Intelligence","Present your work more clearly and professionally.","Profile & Growth",FolderKanban],
["Smart Application","Build a stronger application for the opportunity you want.","Application Tools",BriefcaseBusiness],
["Smart Proposal","Create stronger proposals for GigWay freelance projects.","Application Tools",Sparkles],
["Interview Prep","Prepare for the role before the interview begins.","Interview",ClipboardCheck],
["Interview Practice","Practice your responses and improve before the real interview.","Interview",UserRoundCheck],
] as const
export default function ProfessionalToolsPage(){return <main className="min-h-screen bg-brand-ivory px-4 py-10 sm:py-14"><div className="mx-auto max-w-6xl"><header className="max-w-2xl"><p className="text-caption font-bold tracking-[.16em] text-brand-coral">GIGWAY PROFESSIONAL TOOLS</p><h1 className="mt-3 text-h1 font-extrabold tracking-tight text-brand-midnight">Build your next professional advantage.</h1><p className="mt-3 text-body-lg text-brand-slate">Build a stronger profile, understand opportunities and move your career forward.</p></header><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tools.map(([name,description,category,Icon,available])=>{const body=<article className="h-full rounded-card border border-brand-borderLight bg-white p-5 shadow-soft transition hover:-translate-y-0.5 hover:border-brand-indigo/35 hover:shadow-elevated"><div className="flex items-start justify-between gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-indigo/10 text-brand-indigo"><Icon className="h-5 w-5"/></span><span className={`rounded-pill px-2 py-1 text-caption font-bold ${available?"bg-emerald-50 text-emerald-700":"bg-brand-ivory text-brand-slate"}`}>{available?"Available":"Coming soon"}</span></div><p className="mt-5 text-caption font-bold uppercase tracking-wide text-brand-coral">{category}</p><h2 className="mt-1 text-h3 font-extrabold text-brand-midnight">{name}</h2><p className="mt-2 text-body-sm leading-relaxed text-brand-slate">{description}</p>{available?<p className="mt-5 flex items-center gap-1 text-body-sm font-bold text-brand-indigo">Open tool <ArrowRight className="h-4 w-4"/></p>:<p className="mt-5 flex items-center gap-1 text-caption font-bold text-brand-indigo"><LockKeyhole className="h-3 w-3"/> Included with Pro</p>}</article>;const href=name==="Resume Intelligence"?"/tools/resume-analyzer":"/tools/profile-intelligence";return available?<Link key={name} href={href}>{body}</Link>:<div key={name}>{body}</div>})}</div><section className="mt-10 rounded-card border border-brand-indigo/20 bg-gradient-to-br from-brand-indigo/[.09] to-white p-6 sm:p-8"><p className="text-caption font-bold tracking-[.16em] text-brand-indigo">GIGWAY PRO</p><h2 className="mt-2 text-h2 font-extrabold text-brand-midnight">More opportunities. More professional tools. More ways to grow.</h2><p className="mt-3 max-w-2xl text-body-sm text-brand-slate">Higher limits, more services and portfolio space, unlimited saved opportunities, and full Resume Intelligence. Other Pro tools are coming soon.</p><Link href="/subscribe" className="mt-5 inline-block rounded-xl bg-brand-indigo px-5 py-3 text-body-sm font-bold text-white">Explore Pro — ₹149</Link></section></div></main>}
