"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { normalizeUsername, usernameError } from "@/lib/identity"

type Org = Record<string, any>
const fields = ["name", "username", "website", "logo_url", "cover_url", "tagline", "description", "industry", "company_size", "founded_year", "location", "country"]
export default function OrganizationForm({ organization }: { organization?: Org }) {
  const router = useRouter(); const [data, setData] = useState<Org>(() => Object.fromEntries(fields.map(f => [f, organization?.[f] ?? ""]))); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [availability, setAvailability] = useState<"idle"|"checking"|"available"|"taken">("idle")
  const username = normalizeUsername(data.username)
  useEffect(() => { if (organization?.username === username) return; const invalid = usernameError(username); if (!username || invalid) { setAvailability("idle"); return }; setAvailability("checking"); const timer = setTimeout(async () => { const res = await fetch(`/api/organizations/username?username=${encodeURIComponent(username)}`); const result = await res.json(); setAvailability(result.available ? "available" : "taken") }, 350); return () => clearTimeout(timer) }, [username, organization?.username])
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const invalid = usernameError(username); if (!data.name.trim() || invalid || (!organization && availability !== "available")) { setError(!data.name.trim() ? "Company name is required." : invalid || "Choose an available username."); return }; setSaving(true); setError(""); const endpoint = organization ? `/api/organizations/${organization.username}` : "/api/organizations/create"; const res = await fetch(endpoint, { method: organization ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, username }) }); const result = await res.json().catch(() => ({})); setSaving(false); if (!res.ok) { setError(result.error || "Could not save organization."); return }; router.push(`/@${result.organization.username}`); router.refresh() }
  const input = (key: string, label: string, required = false) => <label className="block text-sm text-[#CBD5E1]">{label}{required && " *"}<Input required={required} value={data[key]} onChange={e => setData(p => ({ ...p, [key]: key === "username" ? e.target.value.toLowerCase().replace(/\s/g, "") : e.target.value }))} className="mt-1 bg-[#0A0A0F] border-[#334155] text-white" /></label>
  return <form onSubmit={submit} className="space-y-4">{input("name", "Company name", true)}{input("username", "Company username", true)}{!organization && availability === "available" && <p className="text-xs text-emerald-400">Username available</p>}{!organization && availability === "taken" && <p className="text-xs text-red-400">Username already taken</p>}<div className="grid sm:grid-cols-2 gap-4">{input("website", "Website")}{input("industry", "Industry")}{input("company_size", "Company size")}{input("founded_year", "Founded year")}{input("location", "Location")}{input("country", "Country")}</div>{input("logo_url", "Logo URL")}{input("cover_url", "Cover image URL")}{input("tagline", "Tagline")}<label className="block text-sm text-[#CBD5E1]">Description<Textarea value={data.description} onChange={e => setData(p => ({ ...p, description: e.target.value }))} className="mt-1 bg-[#0A0A0F] border-[#334155] text-white" /></label>{error && <p className="text-sm text-red-400">{error}</p>}<Button disabled={saving} className="bg-[#6366F1] hover:bg-[#4F46E5]">{saving ? "Saving…" : organization ? "Save Organization" : "Create Company Profile"}</Button></form>
}
