"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Building2, CheckCircle2, Eye, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { ImageUploader } from "@/components/ui/image-uploader"
import { normalizeUsername, usernameError } from "@/lib/identity"

type Org = Record<string, any>
const details = [["website", "Website"], ["industry", "Industry"], ["company_size", "Company size"], ["founded_year", "Founded year"], ["location", "Location"], ["country", "Country"]] as const

export default function OrganizationForm({ organization }: { organization?: Org }) {
  const router = useRouter(); const [step, setStep] = useState(1); const [data, setData] = useState<Org>(() => ({ name: organization?.name ?? "", username: organization?.username ?? "", logo_url: organization?.logo_url ?? "", cover_url: organization?.cover_url ?? "", tagline: organization?.tagline ?? "", description: organization?.description ?? "", website: organization?.website ?? "", industry: organization?.industry ?? "", company_size: organization?.company_size ?? "", founded_year: organization?.founded_year ?? "", location: organization?.location ?? "", country: organization?.country ?? "" })); const [availability, setAvailability] = useState<"idle"|"checking"|"available"|"taken">("idle"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false)
  const username = normalizeUsername(data.username)
  useEffect(() => { if (organization?.username === username) return; const invalid = usernameError(username); if (!username || invalid) { setAvailability("idle"); return }; setAvailability("checking"); const timer = setTimeout(async () => { const response = await fetch(`/api/organizations/username?username=${encodeURIComponent(username)}`); const result = await response.json().catch(() => ({})); setAvailability(result.available ? "available" : "taken") }, 350); return () => clearTimeout(timer) }, [username, organization?.username])
  const field = (key: keyof Org, label: string, required = false) => <label className="block text-sm font-medium text-[#D5D9E4]">{label}{required && <span className="text-[#FB923C]"> *</span>}<Input required={required} value={data[key] ?? ""} onChange={e => setData(prev => ({ ...prev, [key]: key === "username" ? e.target.value.replace(/\s/g, "").toLowerCase() : e.target.value }))} className="mt-1.5 h-11 rounded-xl border-white/10 bg-white/[.045] text-white placeholder:text-[#657084] focus:border-[#8177f7]" /></label>
  const submit = async () => { const invalid = usernameError(username); if (!data.name.trim() || invalid || (!organization && availability !== "available")) { setError(!data.name.trim() ? "Add your company name to continue." : invalid || "Choose an available username."); return }; setSaving(true); setError(""); const response = await fetch(organization ? `/api/organizations/${organization.username}` : "/api/organizations/create", { method: organization ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, username }) }); const result = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) { setError(result.error || "We couldn’t save your company. Please try again."); return }; router.push(`/u/${result.organization.username}`); router.refresh() }
  const titles = organization ? ["Overview", "Branding", "Details", "Preview"] : ["Brand", "Company", "About", "Preview"]
  return <div className="space-y-7"><div className="flex gap-2 overflow-x-auto pb-1">{titles.map((title, index) => <button type="button" key={title} onClick={() => setStep(index + 1)} className={`flex shrink-0 items-center gap-2 rounded-full px-3 py-2 text-xs font-semibold ${step === index + 1 ? "bg-[#6D5DFB] text-white" : "bg-white/[.045] text-[#9099aa]"}`}><span className="grid h-4 w-4 place-items-center rounded-full bg-black/15 text-[10px]">{index + 1}</span>{title}</button>)}</div>
    {step === 1 && <section className="space-y-6"><div><p className="text-xs font-bold tracking-[.16em] text-[#A99FFF]">{organization ? "BRANDING" : "STEP 1 · BRAND"}</p><h2 className="mt-2 text-xl font-bold text-white">Make a recognisable first impression.</h2></div><ImageUploader label="Upload cover" kind="cover" maxMb={8} value={data.cover_url} onChange={cover_url => setData(p => ({ ...p, cover_url }))} /><ImageUploader label="Upload logo" kind="logo" value={data.logo_url} onChange={logo_url => setData(p => ({ ...p, logo_url }))} />{field("name", "Company name", true)}{field("username", "Company username", true)}<p className={`text-xs ${availability === "available" ? "text-emerald-400" : availability === "taken" ? "text-red-400" : "text-[#7d8596]"}`}>{availability === "available" ? "Username available" : availability === "taken" ? "Username already in use" : "Your public company address will be @username."}</p></section>}
    {step === 2 && <section className="space-y-5"><div><p className="text-xs font-bold tracking-[.16em] text-[#A99FFF]">{organization ? "DETAILS" : "STEP 2 · COMPANY"}</p><h2 className="mt-2 text-xl font-bold text-white">Tell people what your company does.</h2></div>{field("tagline", "Tagline")}<div className="grid gap-4 sm:grid-cols-2">{details.map(([key, label]) => field(key, label))}</div></section>}
    {step === 3 && <section className="space-y-4"><p className="text-xs font-bold tracking-[.16em] text-[#A99FFF]">{organization ? "DETAILS" : "STEP 3 · ABOUT"}</p><h2 className="text-xl font-bold text-white">Add the story behind your company.</h2><label className="block text-sm font-medium text-[#D5D9E4]">Description<Textarea value={data.description} onChange={e => setData(p => ({ ...p, description: e.target.value }))} rows={7} className="mt-1.5 rounded-xl border-white/10 bg-white/[.045] text-white focus:border-[#8177f7]" placeholder="What does your team build, and who do you help?" /></label></section>}
    {step === 4 && <section><p className="text-xs font-bold tracking-[.16em] text-[#A99FFF]">STEP 4 · PREVIEW</p><div className="mt-4 overflow-hidden rounded-3xl bg-white/[.045] ring-1 ring-white/10">{data.cover_url ? <img src={data.cover_url} alt="Company cover preview" className="h-32 w-full object-cover" /> : <div className="h-32 bg-gradient-to-br from-[#302b63] to-[#F97316]/40" />}<div className="p-6"><div className="flex items-end gap-4"><div className="-mt-14 grid h-20 w-20 place-items-center overflow-hidden rounded-2xl bg-[#242431] ring-4 ring-[#15151d]">{data.logo_url ? <img src={data.logo_url} alt="Company logo preview" className="h-full w-full object-cover" /> : <Building2 className="text-[#B9B3FF]" />}</div><div><h2 className="font-bold text-white">{data.name || "Your company"}</h2><p className="text-sm text-[#9EA6B8]">@{username || "username"}</p></div></div>{data.tagline && <p className="mt-5 text-[#D4D8E3]">{data.tagline}</p>}<div className="mt-4 flex flex-wrap gap-2 text-xs text-[#9099AA]">{data.industry && <span>{data.industry}</span>}{data.location && <span>· {data.location}</span>}{data.website && <span>· {data.website}</span>}</div></div></div></section>}
    {error && <p className="text-sm text-red-400">{error}</p>}<div className="flex items-center justify-between border-t border-white/8 pt-5"><Button type="button" variant="ghost" disabled={step === 1} onClick={() => setStep(s => s - 1)} className="text-[#B8C0D0]">Back</Button>{step < 4 ? <Button type="button" onClick={() => setStep(s => s + 1)} className="rounded-xl bg-[#6D5DFB] px-5 hover:bg-[#8177f7]">Continue</Button> : <Button type="button" disabled={saving} onClick={submit} className="rounded-xl bg-[#F97316] px-5 font-bold hover:bg-[#FB923C]">{saving ? "Creating…" : organization ? "Save organization" : "Create organization"}</Button>}</div></div>
}
