-- 034: Social Feed Phase 1A. Review/run manually only.
-- Identity model: auth user IDs and profile IDs are distinct namespaces.
CREATE TABLE IF NOT EXISTS posts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),author_user_id uuid NOT NULL,author_profile_id uuid,author_organization_id uuid REFERENCES organizations(id) ON DELETE RESTRICT,post_type text NOT NULL CHECK(post_type IN('text','image','video','document','mixed')),body text,visibility text NOT NULL DEFAULT 'public' CHECK(visibility IN('public','followers')),status text NOT NULL DEFAULT 'published' CHECK(status IN('published','hidden','deleted')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),edited_at timestamptz,deleted_at timestamptz,CONSTRAINT posts_one_display_author CHECK((author_profile_id IS NOT NULL)::int+(author_organization_id IS NOT NULL)::int=1));
CREATE TABLE IF NOT EXISTS post_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),post_id uuid NOT NULL REFERENCES posts(id) ON DELETE CASCADE,media_type text NOT NULL CHECK(media_type IN('image','video','document')),storage_path text NOT NULL,mime_type text NOT NULL,file_name text NOT NULL,file_size_bytes bigint NOT NULL,width integer,height integer,duration_seconds integer,sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS post_likes (post_id uuid NOT NULL REFERENCES posts(id) ON DELETE CASCADE,user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS post_comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),post_id uuid NOT NULL REFERENCES posts(id) ON DELETE CASCADE,user_id uuid NOT NULL,parent_comment_id uuid REFERENCES post_comments(id) ON DELETE CASCADE,body text NOT NULL,status text NOT NULL DEFAULT 'published' CHECK(status IN('published','hidden','deleted')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS post_saves (post_id uuid NOT NULL REFERENCES posts(id) ON DELETE CASCADE,user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS profile_follows (follower_user_id uuid NOT NULL,followed_profile_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(follower_user_id,followed_profile_id));
CREATE TABLE IF NOT EXISTS organization_follows (follower_user_id uuid NOT NULL,organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(follower_user_id,organization_id));
CREATE TABLE IF NOT EXISTS content_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reporter_user_id uuid NOT NULL,post_id uuid REFERENCES posts(id) ON DELETE SET NULL,comment_id uuid REFERENCES post_comments(id) ON DELETE SET NULL,reason text NOT NULL CHECK(reason IN('spam','harassment','misinformation','scam','inappropriate','other')),details text,status text NOT NULL DEFAULT 'open' CHECK(status IN('open','reviewed','actioned','dismissed')),created_at timestamptz NOT NULL DEFAULT now(),CHECK(post_id IS NOT NULL OR comment_id IS NOT NULL));
CREATE INDEX IF NOT EXISTS posts_created_idx ON posts(created_at DESC) WHERE status='published'; CREATE INDEX IF NOT EXISTS posts_user_idx ON posts(author_user_id,created_at DESC); CREATE INDEX IF NOT EXISTS posts_profile_idx ON posts(author_profile_id,created_at DESC); CREATE INDEX IF NOT EXISTS posts_org_idx ON posts(author_organization_id,created_at DESC); CREATE INDEX IF NOT EXISTS post_media_post_idx ON post_media(post_id,sort_order); CREATE INDEX IF NOT EXISTS post_likes_post_idx ON post_likes(post_id); CREATE INDEX IF NOT EXISTS post_comments_post_idx ON post_comments(post_id,created_at); CREATE INDEX IF NOT EXISTS post_saves_user_idx ON post_saves(user_id,post_id); CREATE INDEX IF NOT EXISTS profile_follows_followed_idx ON profile_follows(followed_profile_id); CREATE INDEX IF NOT EXISTS organization_follows_org_idx ON organization_follows(organization_id);
ALTER TABLE posts ENABLE ROW LEVEL SECURITY; ALTER TABLE post_media ENABLE ROW LEVEL SECURITY; ALTER TABLE post_likes ENABLE ROW LEVEL SECURITY; ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY; ALTER TABLE post_saves ENABLE ROW LEVEL SECURITY; ALTER TABLE profile_follows ENABLE ROW LEVEL SECURITY; ALTER TABLE organization_follows ENABLE ROW LEVEL SECURITY; ALTER TABLE content_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public reads public posts" ON posts FOR SELECT USING(status='published' AND visibility='public'); CREATE POLICY "Users manage own likes" ON post_likes FOR ALL USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id); CREATE POLICY "Users read own saves" ON post_saves FOR SELECT USING(auth.uid()=user_id); CREATE POLICY "Users manage own saves" ON post_saves FOR ALL USING(auth.uid()=user_id) WITH CHECK(auth.uid()=user_id); CREATE POLICY "Users read own follows" ON profile_follows FOR SELECT USING(auth.uid()=follower_user_id); CREATE POLICY "Users manage own profile follows" ON profile_follows FOR ALL USING(auth.uid()=follower_user_id) WITH CHECK(auth.uid()=follower_user_id); CREATE POLICY "Users manage own organization follows" ON organization_follows FOR ALL USING(auth.uid()=follower_user_id) WITH CHECK(auth.uid()=follower_user_id); CREATE POLICY "Users create reports" ON content_reports FOR INSERT WITH CHECK(auth.uid()=reporter_user_id);
-- Posts and comments are server-feed API responsibilities. Direct browser writes
-- and comment reads remain blocked until profile/org authority and parent visibility
-- are verified by that API. Media is also server/API managed in V1.
