"use client"

import Link from "next/link"
import { usePathname, useRouter } from "next/navigation"
import { useState } from "react"
import { Building2, CheckCircle2, MapPin, Search, SlidersHorizontal, UserRound, X } from "lucide-react"

type Person = { id: string; full_name: string | null; username: string | null; avatar_url: string | null; tagline: string | null; skills: string[] | null; availability: string | null; is_verified: boolean | null; location: string | null }
type Org = { id: string; name: string; username: string; logo_url: string | null; tagline: string | null; industry: string | null; location: string | null; is_verified: boolean | null }
type Job = { id: string; title: string; company_name: string | null; location: string | null; job_type: string | null; skills_required: string[] | null; created_at: string }
type Project = { id: string; title: string; description: string; budget: number; category: string | null; skills_required: string[] | null; created_at: string }
type Service = { id: string; title: string; price: number; delivery_days: number; category: string | null; tags: string[] | null; image_url: string | null }
export type DiscoverData = { people: Person[]; organizations: Org[]; jobs: Job[]; projects: Project[]; services: Service[] }
const tabs = [["all", "All"], ["people", "People"], ["organizations", "Organizations"], ["jobs", "Jobs"], ["projects", "Projects"], ["services", "Services"]] as const

export default function DiscoverClient({ initialData, query, tab, filters }: { initialData: DiscoverData; query: string; tab: string; filters: Record<string, string> }) {
  const router = useRouter(); const pathname = usePathname()
  const [search, setSearch] = useState(query)
  const update = (changes: Record<string, string>) => { const p = new URLSearchParams(); const all = { q: query, tab, ...filters, ...changes }; Object.entries(all).forEach(([k, v]) => { if (v && !(k === "tab" && v === "all")) p.set(k, v) }); router.push(`${pathname}${p.size ? `?${p}` : ""}`) }
  const activeData = tab === "all" ? initialData : ({ [tab]: initialData[tab as keyof DiscoverData] } as Partial<DiscoverData>)
  const hasResults = Object.values(activeData).some(x => x.length)
  const peopleSkills = [...new Set(initialData.people.flatMap(p => p.skills || []))].slice(0, 8)
  return <div className="min-h-screen bg-brand-ivory pb-14">
    <section className="border-b border-brand-borderLight bg-white"><div className="mx-auto max-w-7xl px-4 py-10 sm:py-14">
      <p className="mb-2 text-caption font-bold tracking-[.16em] text-brand-coral">DISCOVER</p><h1 className="text-h2 font-extrabold text-brand-midnight sm:text-h1">Discover people, work and opportunities.</h1><p className="mt-3 max-w-2xl text-body-sm text-brand-slate sm:text-body-lg">Search professionals, companies, jobs, projects and services across GigWay.</p>
      <form onSubmit={e => { e.preventDefault(); update({ q: search }) }} className="relative mt-7 max-w-4xl"><Search className="absolute left-5 top-1/2 h-5 w-5 -translate-y-1/2 text-brand-indigo" /><input value={search} name="q" onChange={e => setSearch(e.target.value)} placeholder="Search people, skills, companies, jobs, projects or services..." className="w-full rounded-pill border-2 border-brand-indigo/20 bg-white py-4 pl-13 pr-28 text-body-sm text-brand-midnight shadow-elevated outline-none transition focus:border-brand-indigo focus:ring-4 focus:ring-brand-indigo/10" /><button className="absolute right-2 top-2 rounded-pill bg-brand-indigo px-5 py-2 text-body-sm font-bold text-white hover:bg-brand-indigoDark">Search</button></form>
    </div></section>
    <main className="mx-auto max-w-7xl px-4 py-7"><div className="flex gap-2 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{tabs.map(([value, label]) => <button key={value} onClick={() => update({ tab: value })} className={`shrink-0 rounded-pill px-4 py-2 text-body-sm font-semibold ${tab === value ? "bg-brand-indigo text-white" : "border border-brand-borderLight bg-white text-brand-slate hover:text-brand-midnight"}`}>{label}</button>)}</div>
      {(tab === "people" || tab === "organizations") && <div className="mb-6 flex flex-wrap items-center gap-2 rounded-card border border-brand-borderLight bg-white p-3"><SlidersHorizontal className="h-4 w-4 text-brand-indigo" />{tab === "people" && peopleSkills.map(skill => <button key={skill} onClick={() => update({ skill: filters.skill === skill ? "" : skill })} className={`rounded-pill px-3 py-1.5 text-caption font-semibold ${filters.skill === skill ? "bg-brand-indigo text-white" : "bg-brand-ivory text-brand-slate"}`}>{skill}</button>)}<input defaultValue={filters.location} onKeyDown={e => { if (e.key === "Enter") update({ location: (e.target as HTMLInputElement).value }) }} placeholder="Location" className="min-w-24 bg-transparent px-2 py-1 text-caption outline-none" />{tab === "organizations" && <input defaultValue={filters.industry} onKeyDown={e => { if (e.key === "Enter") update({ industry: (e.target as HTMLInputElement).value }) }} placeholder="Industry" className="min-w-24 bg-transparent px-2 py-1 text-caption outline-none" />}</div>}
      {!hasResults ? <div className="rounded-card border border-brand-borderLight bg-white py-20 text-center"><Search className="mx-auto mb-4 h-10 w-10 text-brand-slate/40" /><h2 className="text-h3 font-bold text-brand-midnight">No results for {query ? `'${query}'` : "this search"}.</h2><p className="mt-2 text-body-sm text-brand-slate">Try another skill, person, company or opportunity.</p><button onClick={() => router.push("/explore")} className="mt-5 inline-flex items-center gap-2 text-body-sm font-bold text-brand-indigo"><X className="h-4 w-4" /> Clear Search</button></div> : <div className="space-y-10">{tab === "all" && <p className="text-body-sm text-brand-slate">Grouped results keep every kind of opportunity easy to scan.</p>}{("people" in activeData) && <Group title="People" href="/explore?tab=people" items={activeData.people!} render={p => <PersonCard person={p} />} />}{("organizations" in activeData) && <Group title="Organizations" href="/explore?tab=organizations" items={activeData.organizations!} render={o => <OrganizationCard organization={o} />} />}{("jobs" in activeData) && <Group title="Jobs" href="/explore?tab=jobs" items={activeData.jobs!} render={j => <OpportunityCard item={j} kind="Job" />} />}{("projects" in activeData) && <Group title="Projects" href="/explore?tab=projects" items={activeData.projects!} render={p => <OpportunityCard item={p} kind="Project" />} />}{("services" in activeData) && <Group title="Services" href="/explore?tab=services" items={activeData.services!} render={s => <ServiceCard service={s} />} />}</div>}</main></div>
}
function Group<T extends { id: string }>({ title, href, items, render }: { title: string; href: string; items: T[]; render: (item: T) => React.ReactNode }) { return <section><div className="mb-4 flex items-center justify-between"><h2 className="text-h3 font-extrabold text-brand-midnight">{title}</h2><Link href={href} className="text-body-sm font-bold text-brand-indigo">View all</Link></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">{items.slice(0, 6).map(render)}</div></section> }
function PersonCard({ person: p }: { person: Person }) { return <Link href={p.username ? `/u/${p.username}` : `/freelancers/${p.id}`} className="rounded-card border border-brand-borderLight bg-white p-5 shadow-soft transition hover:-translate-y-0.5 hover:shadow-elevated"><div className="flex gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-brand-indigo/10 font-bold text-brand-indigo">{p.avatar_url ? <img src={p.avatar_url} alt="" className="h-full w-full object-cover" /> : p.full_name?.[0] || <UserRound className="h-5 w-5" />}</div><div className="min-w-0"><div className="flex items-center gap-1"><h3 className="truncate font-bold text-brand-midnight">{p.full_name || "Professional"}</h3>{p.is_verified && <CheckCircle2 className="h-4 w-4 shrink-0 text-brand-indigo" />}</div>{p.username && <p className="text-caption text-brand-slate">@{p.username}</p>}</div></div>{p.tagline && <p className="mt-3 line-clamp-2 text-body-sm text-brand-slate">{p.tagline}</p>}{p.location && <p className="mt-3 flex items-center gap-1 text-caption text-brand-slate"><MapPin className="h-3 w-3" />{p.location}</p>}{p.skills?.length ? <div className="mt-3 flex flex-wrap gap-1">{p.skills.slice(0, 3).map(s => <span key={s} className="rounded-pill bg-brand-indigo/10 px-2 py-1 text-caption text-brand-indigo">{s}</span>)}</div> : null}<span className="mt-4 block text-caption font-bold text-brand-indigo">View Profile</span></Link> }
function OrganizationCard({ organization: o }: { organization: Org }) { return <Link href={`/u/${o.username}`} className="rounded-card border border-brand-borderLight bg-white p-5 shadow-soft transition hover:-translate-y-0.5 hover:shadow-elevated"><div className="flex gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-brand-coral/10 text-brand-coral">{o.logo_url ? <img src={o.logo_url} alt="" className="h-full w-full object-cover" /> : <Building2 className="h-5 w-5" />}</div><div className="min-w-0"><div className="flex items-center gap-1"><h3 className="truncate font-bold text-brand-midnight">{o.name}</h3>{o.is_verified && <CheckCircle2 className="h-4 w-4 text-brand-indigo" />}</div><p className="text-caption text-brand-slate">@{o.username}</p></div></div>{o.tagline && <p className="mt-3 line-clamp-2 text-body-sm text-brand-slate">{o.tagline}</p>}<p className="mt-3 text-caption text-brand-slate">{[o.industry, o.location].filter(Boolean).join(" · ")}</p><span className="mt-4 block text-caption font-bold text-brand-indigo">View Organization</span></Link> }
function OpportunityCard({ item, kind }: { item: Job | Project; kind: "Job" | "Project" }) { const isJob = kind === "Job"; const title = item.title; const tags = item.skills_required; const href = `/${isJob ? "jobs" : "projects"}/${item.id}`; return <Link href={href} className="rounded-card border border-brand-borderLight bg-white p-5 shadow-soft transition hover:-translate-y-0.5 hover:shadow-elevated"><span className="rounded-pill bg-brand-indigo/10 px-2 py-1 text-caption font-bold text-brand-indigo">{kind}</span><h3 className="mt-3 font-bold text-brand-midnight">{title}</h3><p className="mt-1 text-body-sm text-brand-slate">{isJob ? [(item as Job).company_name, (item as Job).location, (item as Job).job_type].filter(Boolean).join(" · ") : (item as Project).description}</p>{tags?.length ? <div className="mt-3 flex flex-wrap gap-1">{tags.slice(0, 3).map(t => <span key={t} className="rounded-pill bg-brand-ivory px-2 py-1 text-caption text-brand-slate">{t}</span>)}</div> : null}<span className="mt-4 block text-caption font-bold text-brand-indigo">View {kind}</span></Link> }
function ServiceCard({ service: s }: { service: Service }) { return <Link href={`/gigs/${s.id}`} className="overflow-hidden rounded-card border border-brand-borderLight bg-white shadow-soft transition hover:-translate-y-0.5 hover:shadow-elevated"><div className="h-28 bg-gradient-to-br from-brand-indigo to-brand-coral">{s.image_url && <img src={s.image_url} alt="" className="h-full w-full object-cover" />}</div><div className="p-5"><span className="text-caption font-bold capitalize text-brand-indigo">{s.category || "Service"}</span><h3 className="mt-1 font-bold text-brand-midnight">{s.title}</h3><p className="mt-2 text-body-sm text-brand-slate">From ₹{s.price.toLocaleString("en-IN")} · {s.delivery_days} day delivery</p><span className="mt-4 block text-caption font-bold text-brand-indigo">View Service</span></div></Link> }
